test(true-up notifications): True-up notifications on invite users modal and global banner
mattermost/mattermost-test-management pull request #10
Opened 2022-11-14 16:56 UTC by yasserfaraazkhan

Ref: PR 
https://github.com/mattermost/mattermost-webapp/pull/11589

<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/10"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-11-14 21:33 UTC, furqanmlk commented on data/test-cases/cloud/true-up-notification/MM-test-case-1.md
> +## Change Test Title
Do we need to update this?

2022-11-15 00:17 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-1.md
> +## Change Test Title
This is optional in PR since it'll be overwritten by permanent test key + title once this PR is merged and saved into Zephyr.

Maybe it would be good to remove this in template so it doesn't create unnecessary overhead? Sounds good?

2022-11-15 00:22 UTC, saturninoabril commented
I'll chime in with the review while Lindy is still away.

2022-11-15 00:43 UTC, saturninoabril approved these changes
Thanks @yasserfaraazkhan! LGTM except for few comments.

2022-11-15 00:43 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-1.md
> +folder: True up Notification
nit: I'd suggest to follow the same epic name - https://mattermost.atlassian.net/browse/MM-47775. Btw, doing so will require update to file path as `cloud/true-up-notifications`
```suggestion
folder: True-up Notifications
```

2022-11-15 00:43 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-1.md
> +team_ownership: []
Please add team owner. If this is for Self-Serve, this could be
```suggestion
team_ownership:
- Self-Serve
```

2022-11-15 00:43 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-1.md
> +- Create 20 (expect current logged in user) users using /test cmd. Such that the active users above 5% and below 10% threshold.
I'd suggest to surround `/test` with backtick to stand out from the statement. Same with other instances.

2022-11-15 00:43 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-1.md
> +- Open invite modal. Verify banner is shown with Yellow color and a message, "Your workspace user count has exceeded your paid license seat count by 1 seat. Notify your Customer Success Manager on yo
```suggestion
- Open invite modal. Verify banner is shown with yellow color and a message, "Your workspace user count has exceeded your paid license seat count by 1 seat. Notify your Customer Success Manager on your next true-up check". Close the modal.
```

2022-11-15 00:43 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-1.md
> +- Verify the banner shouldn't appear banner if the admin had previously dismissed it.
```suggestion
- Verify the banner shouldn't appear if the admin had previously dismissed it.
```

2022-11-15 00:43 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-2.md
> +- Verify the banner shouldn't appear banner if the admin had previously dismissed it.
```suggestion
- Verify the banner shouldn't appear if the admin had previously dismissed it.
```

2022-11-15 00:43 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-2.md
> +team_ownership: []
Same here.

2022-11-15 00:48 UTC, saturninoabril requested changes
For the title, it would be better to change according to our [suggested format](https://github.com/mattermost/mattermost-test-management/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L1-L13). It could be like "test(true-up notifications): True-up notifications on invite users modal"

2022-11-15 02:39 UTC, saturninoabril commented on data/TEST_CASE_TEMPLATE.md
> -
Thanks! LGTM.

2022-11-15 02:41 UTC, saturninoabril approved these changes
Thanks @yasserfaraazkhan!

2022-11-15 02:42 UTC, saturninoabril commented on data/test-cases/cloud/true-up-notification/MM-test-case-1.md
> +## Change Test Title
LGTM, thanks!

2022-11-15 08:38 UTC, Afsoon commented on data/test-cases/cloud/true-up-notifications/MM-test-case-2.md
> +- Have a workspace with test cloud license that has user less limit for testing purposes
```suggestion
- Have a workspace with test self-hosted license that has user less limit for testing purposes
```

2022-11-15 08:54 UTC, yasserfaraazkhan commented
Thank you @Afsoon 🙌

2022-11-15 09:06 UTC, merged