Included first test for GitLab code preview
mattermost/mattermost-test-management pull request #109
Opened 2023-08-23 17:10 UTC by DHaussermann

#### Summary
This is the first test added for the GitLab code preview functionality new in v`1.7.0`

**note**: This is the first of several tests. I wanted to make a commit to work though the process.   

Typical format for test cases:

Test coverage for https://github.com/mattermost/mattermost-plugin-gitlab/pull/299 

#### Is the feature in stable branch or under review?
- [x] Feature in stable branch (master, main)?

#### Test client

- [x] Browser
- [x] Desktop App (version, OS)

2023-08-23 21:56 UTC, saturninoabril requested changes
Thanks @DHaussermann! Looks good to me except one request.

2023-08-23 21:56 UTC, saturninoabril commented on data/test-cases/plugins/gitlab/slash-commands-and-setup/code-preview.md
> +   ex: https://gitlab.com/dhaussermann/dkh-public/-/blob/323cdf25b439e9d01bcb139859b39fc4580e65a1/scipt.js#L11-L12
This will always fail in spell check `scipt` ==> `script`. Can the linked file be changed to `script.js`? Or maybe better point to our org's public repo in GitLab, ex. `https://gitlab.com/mattermost/ci-only/mattermost-omnibus/-/blob/0e5876d95ce9203e9a731e261bc270814f37bc34/scripts/repo-setup.sh#L1-2`?

2023-08-28 06:12 UTC, yasserfaraazkhan approved these changes
Thank you for adding this.

2023-10-02 17:11 UTC, DHaussermann commented on data/test-cases/plugins/gitlab/slash-commands-and-setup/code-preview.md
> +   ex: https://gitlab.com/dhaussermann/dkh-public/-/blob/323cdf25b439e9d01bcb139859b39fc4580e65a1/scipt.js#L11-L12
@saturninoabril the link had `scipt` because the it pointed to a file that had the typo in the file name.

I have now renamed the file being referenced and updated the link. 👍

2023-10-04 09:08 UTC, saturninoabril commented on data/test-cases/plugins/gitlab/slash-commands-and-setup/code-preview.md
> +   ex: https://gitlab.com/dhaussermann/dkh-public/-/blob/323cdf25b439e9d01bcb139859b39fc4580e65a1/script.js#L11-L12
After the change, this should be
```suggestion
   ex: https://gitlab.com/dhaussermann/dkh-public/-/blob/286879ea66708b8cdda736d6b178d6722eb8d5ba/script.js#L11-L12
```

2023-10-04 09:09 UTC, saturninoabril commented on data/test-cases/plugins/gitlab/slash-commands-and-setup/code-preview.md
> +   ex: https://gitlab.com/dhaussermann/dkh-public/-/blob/323cdf25b439e9d01bcb139859b39fc4580e65a1/scipt.js#L11-L12
Thanks!

2023-10-04 09:13 UTC, saturninoabril approved these changes
Thanks @DHaussermann!

2023-10-04 09:13 UTC, merged

2023-10-04 09:50 UTC, saturninoabril commented
Test case saved: [MM-T5454: Code Preview](https://github.com/mattermost/mattermost-test-management/blob/main/data/test-cases/plugins/gitlab/slash-commands-and-setup/MM-T5454.md#mm-t5454-code-preview)