Feat: GM to private channel
mattermost/mattermost-test-management pull request #117
Opened 2023-09-26 10:19 UTC by yasserfaraazkhan

Test cases for https://github.com/mattermost/mattermost/pull/24592

2023-09-27 08:29 UTC, saturninoabril requested changes
Thanks @yasserfaraazkhan! LGTM except for few suggestions.

2023-09-27 08:29 UTC, saturninoabril commented on data/test-cases/channels/channel-menu/test-1.md
> +5. Verify User can see a pop up, with a heading `Convert to Private Channe` and an alert message `Conversation history will be visible to any channel members`.
```suggestion
5. Verify user can see a pop up, with a heading `Convert to Private Channel` and an alert message `Conversation history will be visible to any channel members`.
```

2023-09-27 08:29 UTC, saturninoabril commented on data/test-cases/channels/channel-menu/test-2.md
> +5. Verify User can see a pop up, with a heading `Convert to Private Channe` and an alert message `Unable to convert to a channel because group members are part of different teams`.
```suggestion
5. Verify user can see a pop up, with a heading `Convert to Private Channel` and an alert message `Unable to convert to a channel because group members are part of different teams`.
```

2023-09-27 08:29 UTC, saturninoabril commented on data/test-cases/channels/channel-menu/test-2.md
> +![Screenshot](/data/asset/Error_converting_GM.png)
This should be in a format where the image can be accessed by Zephyr.
```suggestion
![Screenshot](https://raw.githubusercontent.com/mattermost/mattermost-test-management/main/data/asset/Error_converting_GM.png)
```

2023-09-28 11:01 UTC, harshilsharma63 approved these changes

2023-10-04 08:48 UTC, saturninoabril approved these changes
Thanks @yasserfaraazkhan!

2023-10-04 08:49 UTC, merged