feat: Highlight Keywords without notification
mattermost/mattermost-test-management pull request #119
Opened 2023-10-05 18:05 UTC by yasserfaraazkhan

2023-10-05 18:13 UTC, M-ZubairAhmed requested changes
I was hoping we could have even more test cases rather than just the two so we can have good amount of e2e coverage

2023-10-05 18:30 UTC, yasserfaraazkhan commented
Sure @M-ZubairAhmed ,
I'm putting down according to Acceptance criteria for the feature. observed a[ behaviour here ](https://github.com/mattermost/mattermost/pull/24050#issuecomment-1749411775).

will add few more.

2023-10-11 08:02 UTC, M-ZubairAhmed requested changes
We will also need to included the changes after the Upsell discussion on this feature. So will wait for those

2023-10-11 08:02 UTC, M-ZubairAhmed commented on data/test-cases/channels/settings/test-1.md
> +6. Verify in **User A**'s account that the phrase is highlighted.
this is a bit confusing.
posing of user B phrase highlights in user A?

2023-10-11 10:45 UTC, yasserfaraazkhan commented on data/test-cases/channels/settings/test-1.md
> +6. Verify in **User A**'s account that the phrase is highlighted.
I'll re-phrase it.
mainly the Steps is to see, if USER B posts the keywords of USER A, would it be highlighted.

2023-10-11 10:46 UTC, yasserfaraazkhan commented on data/test-cases/channels/settings/test-1.md
> +6. Verify in **User A**'s account that the phrase is highlighted.
@M-ZubairAhmed

2023-10-16 22:14 UTC, marianunez requested changes
Thanks @yasserfaraazkhan! Base test cases LGTM, could you include the test cases for the upsell scenarios discussed last week?

2023-10-16 22:14 UTC, marianunez commented on data/test-cases/channels/settings/test-1.md
> +5. Verify the Phrase is Highlighted by a yellow background
Could we add an additional step to verify that the phrase does **not** show in the mentions section in the RHS (like the highlight keywords do)

2023-10-20 21:38 UTC, marianunez commented on data/test-cases/channels/settings/test-0.md
> +7. Verify that the button turns grey and is disabled. The button will have text `Notification sent!`
This would be the end user case, can we add the admin case?

2023-10-20 21:38 UTC, marianunez commented on data/test-cases/channels/settings/test-0.md
> +Scenario: When instance is on a Professsional license or an Enterprise Trial license.
```suggestion
Scenario: When instance is on a Professsional, Enterprise license or an Enterprise Trial license.
```

2023-10-22 17:10 UTC, yasserfaraazkhan commented on data/test-cases/channels/settings/tes.md
> +5. Verify that a modal with title `Highlighted Keywords without notifications with Mattermost Professional` appears.
Hi @marianunez @abhijit-singh ,
will the title contain `Upgrade to use ..` like in the below example  

<img width="623" alt="image" src="https://github.com/mattermost/mattermost-test-management/assets/15979783/1c5ed92d-6fa5-455c-9f6f-338e514342ea">

2023-10-23 17:11 UTC, M-ZubairAhmed requested changes

2023-10-23 17:11 UTC, M-ZubairAhmed commented on data/test-cases/channels/settings/tes.md
> +7. Verify that the pricing modal is opened.
Scenario : When instance is on a Professsional, Enterprise license or an Enterprise Trial license.

Is missing

2023-10-23 17:11 UTC, M-ZubairAhmed commented on data/test-cases/channels/settings/test-3.md
what is that we are testing differently in this test case compared to test-2?

2023-10-23 17:20 UTC, yasserfaraazkhan commented on data/test-cases/channels/settings/tes.md
sure. before commit it wont have any impact, after the review are done , we run `deno task save` the file names are replaced by `MM-T{number}`

2023-10-23 17:25 UTC, yasserfaraazkhan commented on data/test-cases/channels/settings/test-3.md
test-1 : Same user setting keywords and verifying Other user's post containing keywords are highlighted 
test-2: Focused on Modal, if the user can save the words and phrases 
@M-ZubairAhmed

2023-10-23 17:28 UTC, M-ZubairAhmed commented on data/test-cases/channels/settings/test-3.md
i see

2023-10-23 17:29 UTC, yasserfaraazkhan commented on data/test-cases/channels/settings/tes.md
> +7. Verify that the pricing modal is opened.
@M-ZubairAhmed 
for admin, in this scenario, the feature is usable right? 
I felt its common flow for Admin & User, have put it up in Test-0 file.

2023-10-23 17:55 UTC, M-ZubairAhmed commented on data/test-cases/channels/settings/tes.md
> +7. Verify that the pricing modal is opened.
i would still put in for being more descripive

2023-10-23 17:56 UTC, M-ZubairAhmed approved these changes
Just one comment above

2023-10-24 02:39 UTC, marianunez approved these changes
Thanks @yasserfaraazkhan! LGTM - small note of a verification to add below

2023-10-24 02:39 UTC, marianunez commented on data/test-cases/channels/settings/test-1.md
> +6. Click on the post and verify the Phrase is Highlighted by a yellow background in the RHS.
We also want to check that the highlighted words without notification DO NOT show when you click on the Mentions tab (mentions are for your highlight words WITH notification): 
<img width="542" alt="Screen Shot 2023-10-23 at 10 37 45 PM" src="https://github.com/mattermost/mattermost-test-management/assets/936315/eb83452f-cc4a-47fd-be9e-3a32268e87f7">

2023-10-24 06:41 UTC, yasserfaraazkhan commented on data/test-cases/channels/settings/test-1.md
> +6. Click on the post and verify the Phrase is Highlighted by a yellow background in the RHS.
thank you Maria. I have added this step

2023-10-24 07:08 UTC, merged