add test case
mattermost/mattermost-test-management pull request #147
Opened 2024-01-02 17:50 UTC by yasserfaraazkhan

Dev PR: https://github.com/mattermost/mattermost/pull/2 579 7

2024-01-03 06:06 UTC, M-ZubairAhmed requested changes
Please recheck the tests because we are not implementing the bands limit anymore check the spec https://docs.google.com/document/d/1RYL-6WrZdMjZYL84PvS_PsRdcnU3gXVCAOSIz5zl8Do/edit?usp=sharing

2024-01-03 06:06 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/Airgapped.md
> +1. Have 1 Free instance running Enterprise edition with 9001 users running as an airgapped instance
10K is the limit https://docs.google.com/document/d/1RYL-6WrZdMjZYL84PvS_PsRdcnU3gXVCAOSIz5zl8Do/edit?usp=sharing

2024-01-03 06:06 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/Airgapped.md
> +6. Verify the global banner is not showing up.
this should be another scenario it cannot happen in a single test case

2024-01-03 06:06 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/Airgapped.md
> +**Scenario**: When user is running enterprise edition
this is for admins not users

2024-01-03 06:06 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/Airgapped.md
> +**Scenario**: When user is running enterprise edition
```suggestion
**Scenario**: When admin is running enterprise edition without license
```

2024-01-03 06:06 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/Airgapped.md
> +6. Verify the global banner is not showing up.
another case " when admin is running enterprise edition with license"
- should not show the banner when limit is breached

2024-01-09 12:33 UTC, M-ZubairAhmed requested changes

2024-01-09 12:33 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/BannerMoreThan10k.md
> +7. Verify the global banner is not showing up.
lets add refresh after the license added as well

2024-01-09 12:33 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/BannerMoreThan10k.md
> +3. Verify a Red global banner should be displayed with a message saying `Your user count exceeds the maximum users allowed. Upgrade to Mattermost Professional or Mattermost Enterprise to continue usi
before this refresh

2024-01-09 12:33 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/BannerMoreThan10k.md
> +5. Verify a section with header `Upgrade to Mattermost Professional or Mattermost Enterprise` is shown in red background.
not in the spec

2024-01-09 12:33 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/Airgapped.md
> +6. Verify the global banner is not showing up.
refresh the app

2024-01-09 12:33 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/Airgapped.md
> +1. Login into Free instance running Enterprise edition with 10,000 users.
not free instance

2024-01-10 05:48 UTC, yasserfaraazkhan commented on data/test-cases/self-hosted/user-limits/BannerMoreThan10k.md
> +7. Verify the global banner is not showing up.
currently, after license the banners automatically disappear after adding license eg: the trial banner

2024-01-10 19:25 UTC, M-ZubairAhmed requested changes

2024-01-10 19:25 UTC, M-ZubairAhmed commented on data/test-cases/self-hosted/user-limits/Airgapped.md
> +2. Refresh the app and verify the banner is not displayed when user crosses maximum user limit.
add scenario for air gapped team edition as well,

2024-01-11 15:25 UTC, M-ZubairAhmed approved these changes

2024-01-14 16:49 UTC, marianunez approved these changes
Thanks @yasserfaraazkhan! LGTM

2024-01-15 06:14 UTC, saturninoabril approved these changes
Thanks Yasser! Left minor comments, once resolve all good to me. Approving now.

2024-01-15 06:14 UTC, saturninoabril commented on data/test-cases/self-hosted/user-limits/BannerMoreThan10k.md
> +name: "Mattermost Enterprise and Team Edition should show a non dismissable global banner when instance has active users more than 10,000"
I suggest to omit "Mattermost" in the title for it's understandable already. In addition, I believe it should be "non-dismissible" although I can see we're not consistent as well.

```suggestion
name: "Enterprise and Team Edition should show a non-dismissible global banner when instance has active users more than 10,000"
```

2024-01-15 06:14 UTC, saturninoabril commented on data/test-cases/self-hosted/user-limits/BannerMoreThan10k.md
> +3. Refresh the app and verify a Red global banner should be displayed with a message saying `Your user count exceeds the maximum users allowed. Upgrade to Mattermost Professional or Mattermost Enterp
Minor correction, please do the same to other similar usage.

```suggestion
3. Refresh the app and verify a red global banner is displayed with a message saying `Your user count exceeds the maximum users allowed. Upgrade to Mattermost Professional or Mattermost Enterprise to continue using Mattermost.`. There should also be a `Learn more` button.
```

2024-01-16 10:31 UTC, merged