Create test cases for auto-mute/unmute channels
mattermost/mattermost-test-management pull request #151
Opened 2024-01-09 13:34 UTC by yasserfaraazkhan

JIRA: https://mattermost.atlassian.net/browse/MM-55641

2024-01-12 16:39 UTC, marianunez reviewed
Thanks @yasserfaraazkhan, left some minor comments below

2024-01-12 16:39 UTC, marianunez commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-2.1.md
> +4. Verify that the setting is successfully updated.
After the setting is updated, validate that the behaviors of muting or unmutting works as expected depending on their selection.

2024-01-12 20:12 UTC, hmhealey requested changes

2024-01-12 20:12 UTC, hmhealey commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-2.2.md
> +3. Toggle the auto-mute setting.
While we'd discussed a separate auto-mute setting previously, I think we decided to just have a single setting for the primary platform, so this case is the same as 2-1

2024-01-12 20:12 UTC, hmhealey commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-2.3.md
> +1. Connect Mattermost account.
Since it'll determine what the auto-muting behaviour is, what's the user's primary platform going to be in this case?

2024-01-12 20:12 UTC, hmhealey commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-3.2.md
> +3. Verify that the channel is muted.
Like Maria's comments surrounding this one, this'll only happen if their platform is MS Teams

2024-01-12 20:12 UTC, hmhealey commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-4.1.md
> +1. Connect Mattermost account.
And here

2024-01-17 11:24 UTC, larkox commented on data/test-by-folder.json
> +      "Verify that the user is prompted to choose their primary platform (Mattermost or MS Teams) during the initial account connection"
Not sure if already covered by other tests, but there are two things that would be nice to have verified:
- Confirm that the selection of the primary platform during initial account connection
  - Does what it has to do (mute or not mute the proper channels)
  - Shows in the user settings

2024-01-23 10:56 UTC, yasserfaraazkhan commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-3.1.md
> +3. Verify that the channel is muted.
I'll add scenarios, when the primary selcetion is Mattermost and when it is MSTeam

2024-01-23 10:59 UTC, yasserfaraazkhan commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-2.3.md
> +1. Connect Mattermost account.
@hmhealey in all the test-case- 2.x the primary platform is MS Team
i'll add that as a setup step

2024-01-23 11:01 UTC, yasserfaraazkhan commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-2.3.md
> +1. Connect Mattermost account.
@hmhealey I'll add scenario where the Initial selection is either MS team or Mattermost, and the user changes it from User Settings

2024-01-23 11:44 UTC, yasserfaraazkhan commented on data/test-by-folder.json
> +      "Verify that the user is prompted to choose their primary platform (Mattermost or MS Teams) during the initial account connection"
Thank you Daniel, I've added these now.

2024-01-26 18:42 UTC, hmhealey commented on data/test-by-folder.json
> +      "Verify that the user is prompted to choose their primary platform (Mattermost or MSTeamss) during the initial account connection"
I just noticed that there's a few times throughout these steps which have "MSTeamss" written with an extra S

2024-01-26 18:46 UTC, hmhealey commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-3.2.md
> +2. Create a DM/GM channel and link it with MSTeamss using slash command `/msteams-sync link <msteams-teams-id> <msteams-channel-id>`.
Yeah, I just confirmed with Maria that these are always linked, so this step can be skipped for DM/GMs

2024-02-06 08:19 UTC, yasserfaraazkhan commented on data/test-by-folder.json
> +      "Verify that the user is prompted to choose their primary platform (Mattermost or MSTeamss) during the initial account connection"
done

2024-02-06 08:23 UTC, yasserfaraazkhan commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-5.1.md
@hmhealey, I'll remove it form this pr. Thought of adding, while I was at it.

2024-02-06 08:26 UTC, yasserfaraazkhan commented on data/test-cases/plugins/ms-teams-sync/mute-unmute/test-3.2.md
> +2. Create a DM/GM channel and link it with MSTeamss using slash command `/msteams-sync link <msteams-teams-id> <msteams-channel-id>`.
thank you Harrison. I've removed this.

2024-02-13 17:03 UTC, hmhealey approved these changes
🎉

2024-02-13 18:06 UTC, merged