User Survey plugin test cases
mattermost/mattermost-test-management pull request #166
Opened 2024-03-19 13:48 UTC by yasserfaraazkhan

2024-03-26 04:45 UTC, harshilsharma63 commented
Will review it this week. Sorry, trying to catch up on system console work.

2024-04-01 04:45 UTC, harshilsharma63 requested changes

2024-04-01 04:45 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-1-cadence.md
> +3. Verify that the "Survey Cadence" is set to "Quarterly" by default.
For the first release we're skipping the ability to select an automatic cadence. The admin will be able to specify the date and time when the survey starts. It looks like this -

![Screenshot 2024-04-01 at 10 01 34 AM](https://github.com/mattermost/mattermost-test-management/assets/18575143/176c2207-1e0d-4512-b9bf-c8e1a1a8c8e5)

2024-04-01 04:45 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-1-cadence.md
> +4. Verify the date corresponds to the last day of the current quarter (March 31st, June 30th, September 30th, December 31st).
With the removal of automatic cadence options )monthly, quarterly etc., the default value displayed for date will be 30 days from current date and the default time will be `09:00`. Note that the time will be in 24 hours format.

2024-04-01 04:45 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-1-cadence.md
> +Scenario 2: Change Cadence to Twice a Year
So basically scenario 2 and 3 are not applicable for the first release.

2024-04-01 04:45 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-1-cadence.md
> +Scenario 2: Change Cadence to Twice a Year
But definitally valid and applicable for next iteration.

2024-04-01 04:45 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-2-configure.md
> +4. Save the changes.
This many not work exactly this way. The mechanism of saving and validating settings in plugins is not the best and simplest. I'm still figuring out when and how to best show validation errors so lets keep this open for now and we can update the exact step to reproduce this later on. But yeah, we need to add those validations.

2024-04-01 04:45 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-3-exclude-team.md
> +9. Exclude Team C and launch a survey
In this step are we adding team c to excluded teams (so basically the field will show team A, B and C as excluded), right? If so, ca we add the case of excluding only team C and verifying no user gets the survey? As that was the confusing case.

2024-04-01 04:45 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-4-update-question-wording.md
> +name: "User Surveys | Exclude Team from survey"
You probably forgot to update this file, this is the same as exclude team spec  😝

2024-04-01 04:46 UTC, harshilsharma63 commented
Great work! Lot of great cases bringing clarity to requirements.

2024-04-15 20:00 UTC, yasserfaraazkhan commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-2-configure.md
> +4. Save the changes.
I'll adjsut the steps one, we have a way to validate

2024-04-15 20:09 UTC, yasserfaraazkhan commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-3-exclude-team.md
> +9. Exclude Team C and launch a survey
It was Just 1 team at a time.
what would be the case if we add just Team C, no one will get the survey, right?

2024-05-22 03:11 UTC, harshilsharma63 requested changes

2024-05-22 03:11 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-4-include-team.md
> +8. Verify that User 1 receives the Survey.
If user 1 has opened Mattermost while this survey was running and user 1 was in an excluded team, they will not get the survey immediately on moving out of excluded team and moving into a non-excluded team. The team mapping of a user is cached by the plugin for 2 hours. So, user 1 will get the survey 2 hours after the latest time they opened Mattermost in webapp/desktop app.

2024-05-22 03:11 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-3-exclude-team.md
> +6. Verify that the fields displays team names to be excluded.
If an excluded team no longer exists (for example, if its archived), the plugin will display team ID instead of team name.

2024-05-22 03:11 UTC, harshilsharma63 commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-2-configure.md
> +Scenario 3: Try to Set Invalid Duration (less than 5 or greater than 30)
I missed communicating this but we removed this limitation of a max and min values for survey expiry. Any value greater than 0 is a valid value now.

2024-05-22 17:50 UTC, marianunez approved these changes
Thanks Yasser! Left some comments below

2024-05-22 17:50 UTC, marianunez commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-2-configure.md
> +3. Verify a message is displayed syaing `Survey expired on <Month> <Day>, <Year>`.
We should also verify that the unanswered survery posts will be grayed out and they cannot send a response.

2024-05-22 17:50 UTC, marianunez commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-5-previous-surveys.md
> +6. Should be able to download the Survey responses.
Can we include to validate the contents of the survey dowload that it should be a zip file with the two files: survey metadata and responses?

2024-05-27 10:03 UTC, yasserfaraazkhan commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-4-include-team.md
> +8. Verify that User 1 receives the Survey.
sure, I have added a note below.

2024-05-29 06:12 UTC, yasserfaraazkhan commented on data/test-cases/plugins/nps-plugin/new-nps-plugin/test-2-configure.md
> +Scenario 3: Try to Set Invalid Duration (less than 5 or greater than 30)
removed the scenario

2024-06-01 09:51 UTC, merged