test(MS Teams plugin): bot messages for v1.10
mattermost/mattermost-test-management pull request #168
Opened 2024-03-28 13:50 UTC by lieut-data

#### Summary
Document test cases for two classes of bot messages introduced with the MS Teams plugin v1.10.

#### Is the feature in stable branch or under review?
- [x] Feature in stable branch (master, main)? Yes, shipped in v1.10
- [x] Feature still under review? No, already merged.

#### Test server
https://msteams-sync-test.test.mattermost.cloud/

#### Test client
No specific requirements.

- [x] Browser
- [x] Mobile App (version, OS)
- [x] Desktop App (version, OS)

2024-03-29 07:32 UTC, lindy65 commented
Hey @lieut-data - this is awesome! Thank you for adding these tests :)

One comment...  In all the tests except for the last one, the verification step at the end of each test says `Very` instead of `Verify`

Otherwise looks good to me!

2024-03-29 07:39 UTC, lindalumitchell approved these changes
Yes, this is terrific, thanks Jesse! No additional suggestions from me other than what Lindy mentioned about "very" vs. "verify". 👍

2024-03-29 17:02 UTC, lieut-data commented
Thanks, @lindalumitchell & @lindy65. I'm guessing there's something about the `deno` that I need to do to merge? I'm uncertain how to interpret the CI failure.

2024-03-29 17:40 UTC, lindalumitchell commented
Ah yes, it's failing to validate on `"customFields.Team Ownership" with unexpected value of "MS Teams"` because the Team Ownership list is out of date. 

Opened https://github.com/mattermost/mattermost-test-management/pull/169 to update that list. Since we're into the weekend for many folks such as Saturn, to avoid waiting until next week would you be willing to review that PR, @lieut-data ? Unconventional, but these are very low-risk changes.

2024-03-29 19:53 UTC, lieut-data commented
@lindalumitchell, reviewed, but alas I think a code owner is required on that repo.

2024-03-29 20:08 UTC, lindalumitchell commented
Ah you're right. Thanks for reviewing it anyway, and I'm out for two weeks starting Monday, but next week after other folks are back and can get that reviewed and merged in, I think this one should be able to pass validation and be merged as well.

2024-04-01 05:21 UTC, saturninoabril requested changes
Thanks @lieut-data! Overall looks good except for test structure.

For codeowner, I think I'll be removing it from this repo for this has been stable for a while and very much open to everyone. (will address separately)

2024-04-01 05:21 UTC, saturninoabril commented on data/test-cases/plugins/ms-teams-sync/bot-messages/connection-prompt/MM-TXXX0.md
> +Send a direct message to a remote user (e.g. `@msteams_user`)
Multiple "Step #n" in Zephyr looks like in the screenshot, with each "Step" having "test step or steps", test data (optional) and expected result (required). A bit confusing but in general, it's a sub-test case (if you will). Each step has its own test result and should be mapped properly between test automation and Zephyr.
<img width="1176" alt="Screenshot 2024-04-01 at 1 04 32 PM" src="https://github.com/mattermost/mattermost-test-management/assets/5334504/7c0cbf6c-344b-4166-8629-1a828f8737f5">

With that, the step to disconnect from MS teams can be combined to the actual step (`Step #2`) or could be as `Precondition`.

```suggestion
**Precondition**

Disconnect from MS Teams, if necessary, via `/msteams disconnect`.

**Step 1**

Send a direct message to a remote user (e.g. `@msteams_user`)
```

2024-04-01 06:45 UTC, lindy65 approved these changes
Thanks @lieut-data - I see Saturn has helped with comments about test structure so I'll go ahead and approve this PR as you can request final review from him after addressing requested changes 👍

2024-04-04 07:39 UTC, saturninoabril commented
@lieut-data Let me know if you need anything so we can merge as soon as possible.

2024-04-04 13:13 UTC, lieut-data commented on data/test-cases/plugins/ms-teams-sync/bot-messages/connection-prompt/MM-TXXX0.md
> +Send a direct message to a remote user (e.g. `@msteams_user`)
Thanks, @saturninoabril! I've updated as recommended -- let me know if that works?

2024-04-04 13:18 UTC, saturninoabril approved these changes
Thanks @lieut-data, LGTM.

2024-04-04 13:18 UTC, merged