feat: Test cases for Scheduled Message feature
mattermost/mattermost-test-management pull request #183
Opened 2024-09-13 11:29 UTC by yasserfaraazkhan

JIRA: https://mattermost.atlassian.net/browse/MM-60375

2024-09-17 21:04 UTC, marianunez requested changes
Thanks @yasserfaraazkhan! Added some comments on additional cases we want to include. 

Also, for the first version I believe we will be supporting moving a draft to a scheduled post. Is this correct @harshilsharma63 ? If so, we need to include test cases for add/remove schedule to drafts

2024-09-17 21:04 UTC, marianunez commented on data/test-cases/channels/schedule-messages/1-Create-Schedule-Messages.md
> +4. Choose a pre-defined Date from the options.
Can we verify the timezone behavior for scheduling? I believe the expected behavior is the date and time dialog is in the users configured timezone, can you confirm @harshilsharma63 ?

2024-09-17 21:04 UTC, marianunez commented on data/test-cases/channels/schedule-messages/1-Create-Schedule-Messages.md
> +name: "Verify User can create a scheduled message in DM/GM/Channel"
Can we also test messages that include attachments and post priority set?

2024-09-18 14:29 UTC, yasserfaraazkhan commented on data/test-cases/channels/schedule-messages/1-Create-Schedule-Messages.md
> +name: "Verify User can create a scheduled message in DM/GM/Channel"
Sure Maria. Had made a checklist. Will also add in zephyr.

2024-09-24 03:48 UTC, harshilsharma63 commented on data/test-cases/channels/schedule-messages/1-Create-Schedule-Messages.md
> +4. Choose a pre-defined Date from the options.
Thats correct, it should be in the user's configured TZ, not the timezone of the browser.

2024-09-24 23:08 UTC, lindalumitchell approved these changes
Nice, @yasserfaraazkhan! I added a bunch of nitpicky suggestions, plus I've started auditing the priorities set on our test cases, so these should be P3 in our custom priority field, as noted. Approving since the substance looks great; you can decide about my suggestions. :)

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/4-Failed-Schedule-Message.md
> +### Scenario 7: Verify Schedule message fails if the root post is moved to another team channel.
```suggestion
### Scenario 7: Verify Schedule message fails if the root post is moved to another team.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/4-Failed-Schedule-Message.md
> +3. Log into User B's account and create a threaded schedule message to the root post.
```suggestion
3. Log into User B's account and create a threaded scheduled message on the root post.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/4-Failed-Schedule-Message.md
> +6. Goto Scheduled messages tab.
```suggestion
6. Go to Scheduled messages tab.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/5-Failed-Server-outage-Schedule-Message.md
> +name: "Verify if the Failed Scheduled message is sent out after server recovered from and Outage issue"
```suggestion
name: "Verify if the Failed Scheduled message is sent out after server recovered from an outage issue"
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/5-Failed-Server-outage-Schedule-Message.md
> +priority_p1_to_p4: P2 - Core Functions (Do core functions work?)
```suggestion
priority_p1_to_p4: P3 - Deep Functions (Do extensive scenarios work?)
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/5-Failed-Server-outage-Schedule-Message.md
> +   - Option 1: User Jmeter or k6 tool to generate huge traffic on the server.
```suggestion
   - Option 1: Use Jmeter or k6 tool to generate huge traffic on the server.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/5-Failed-Server-outage-Schedule-Message.md
> +### Scenario 2: The server does not recover within a timestamp of 30 minutes. Messages is marked as Failed.
```suggestion
### Scenario 2: The server does not recover within a timestamp of 30 minutes. Message is marked as Failed.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/6-Add-Schedule-to-Draft.md
> +priority_p1_to_p4: P2 - Core Functions (Do core functions work?)
```suggestion
priority_p1_to_p4: P3 - Deep Functions (Do extensive scenarios work?)
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/6-Add-Schedule-to-Draft.md
> +name: "Verify User can create a Schedule message from the Draft Page"
```suggestion
name: "Verify User can create a scheduled message from the Draft Page"
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/6-Add-Schedule-to-Draft.md
> +3. Goto Drafts page.
```suggestion
3. Go to Drafts page.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/6-Add-Schedule-to-Draft.md
> +12. GOto the DM/GM/Channel where the draft was created.
```suggestion
12. Go to the DM/GM/Channel where the draft was created.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/7-Remove-Schedule-and-Move-to-Draft.md
> +priority_p1_to_p4: P2 - Core Functions (Do core functions work?)
```suggestion
priority_p1_to_p4: P3 - Deep Functions (Do extensive scenarios work?)
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/7-Remove-Schedule-and-Move-to-Draft.md
> +2. Goto Scheduled tab.
```suggestion
2. Go to Scheduled tab.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/7-Remove-Schedule-and-Move-to-Draft.md
> +9. Goto Scheduled tab.
```suggestion
9. Go to Scheduled tab.
```

2024-09-24 23:08 UTC, lindalumitchell commented on data/test-cases/channels/schedule-messages/7-Remove-Schedule-and-Move-to-Draft.md
> +11. GOto the DM/GM/Channel where the draft was created.
```suggestion
11. Go to the DM/GM/Channel where the draft was created.
```

2024-09-24 23:09 UTC, lindalumitchell approved these changes
Nice, @yasserfaraazkhan! I added a bunch of nitpicky suggestions, plus I've started auditing the priorities set on our test cases, so I marked that these should be P3 in our custom priority field. Approving since the substance looks great on the test cases; you can decide about my suggestions. :)

2024-10-24 08:40 UTC, yasserfaraazkhan commented on data/test-cases/channels/schedule-messages/1-Create-Schedule-Messages.md
> +4. Choose a pre-defined Date from the options.
added

2024-10-25 11:07 UTC, harshilsharma63 approved these changes

2024-10-28 18:52 UTC, marianunez approved these changes
Thanks @yasserfaraazkhan!

2024-10-29 07:20 UTC, merged