Feat: Notifications Banner
mattermost/mattermost-test-management pull request #184
Opened 2024-09-16 17:10 UTC by yasserfaraazkhan

Jira: https://mattermost.atlassian.net/browse/MM-60477

2024-09-19 11:01 UTC, M-ZubairAhmed requested changes

2024-09-25 09:26 UTC, yasserfaraazkhan commented on data/test-cases/notifications-banner/1-Enable-disable-notif.md
> +### Scenario: User Deny's the desktop notifications on WINDOWS or MAC OS
done

2024-09-25 09:27 UTC, yasserfaraazkhan commented on data/test-cases/notifications-banner/1-Enable-disable-notif.md
Got it. Added Chrome, Firefox, Edge and Safari

2024-10-12 02:13 UTC, lindalumitchell approved these changes
Nice, Yasser, thanks! Just a few nit-picky suggestions. :)

2024-10-12 02:13 UTC, lindalumitchell commented on data/test-cases/notifications-banner/1-Enable-disable-notif.md
> +### Scenario: User Deny's the desktop notifications on WINDOWS / MAC / Ubuntu OS
```suggestion
### Scenario: User Denies the desktop notifications on WINDOWS / MAC / Ubuntu OS
```

2024-10-12 02:13 UTC, lindalumitchell commented on data/test-cases/notifications-banner/1-Enable-disable-notif.md
> +9. Verify the notification pop-up are not seen.
```suggestion
9. Verify the notification pop-up is not seen.
```

2024-10-12 02:13 UTC, lindalumitchell commented on data/test-cases/notifications-banner/1-Enable-disable-notif.md
> +13. Expand "Desktop and mobile notification section".
```suggestion
13. Expand "Desktop and mobile notifications" section.
```

2024-10-12 02:13 UTC, lindalumitchell commented on data/test-cases/notifications-banner/1-Enable-disable-notif.md
> +### Scenario: User Deny's the desktop notifications on Browsers Chrome/Safari/Firefox/Edge
```suggestion
### Scenario: User Denies the desktop notifications on browsers Chrome/Safari/Firefox/Edge
```

2024-10-12 02:13 UTC, lindalumitchell commented on data/test-cases/notifications-banner/2-Mobile-disable-notif.md
> +name: "Enable/Disabled notification on Mobile app"
```suggestion
name: "Enable/Disable notification on Mobile app"
```

2024-10-12 02:13 UTC, lindalumitchell commented on data/test-cases/notifications-banner/2-Mobile-disable-notif.md
> +priority_p1_to_p4: P2 - Core Functions (Do core functions work?)
```suggestion
priority_p1_to_p4: P3 - Deep Functions (Do extensive scenarios work?)
```

2024-10-22 08:21 UTC, yasserfaraazkhan commented on data/test-cases/notifications-banner/1-Enable-disable-notif.md
> +### Scenario: User Deny's the desktop notifications on WINDOWS / MAC / Ubuntu OS
@lindalumitchell  Haha. I cant belive I wrote "Deny's"

I was hungry 🌯

2024-10-24 08:23 UTC, merged