test(insight, ad-ldap and user groups) added test cases
mattermost/mattermost-test-management pull request #19
Opened 2022-11-23 20:28 UTC by furqanmlk

#### Summary

https://mattermost.atlassian.net/browse/MM-41906
https://mattermost.atlassian.net/browse/MM-46112
https://mattermost.atlassian.net/browse/MM-47145
https://mattermost.atlassian.net/browse/MM-48186
https://mattermost.atlassian.net/browse/MM-44347
https://mattermost.atlassian.net/browse/MM-44353

#### Is the feature in stable branch or under review?
- [x] Feature in stable branch (master)

#### Test client
- [x] Desktop App (version, OS)

2022-11-23 20:49 UTC, yasserfaraazkhan requested changes
try `deno task validate` locally it should suggest folder names

2022-11-23 20:49 UTC, yasserfaraazkhan commented on data/test-cases/suite/ad-ldap/MM-test-case-1.md
> +folder: suite
@furqanmlk I think this should be AD-LDAP

2022-11-23 20:49 UTC, yasserfaraazkhan commented on data/test-cases/suite/enterprise/user groups/MM-Test-Case-1.md
> +folder: user groups
@furqanmlk here I think, the folder name should be `enterprise/user-group` (not in the file, but the folder should have `-`)

2022-11-23 20:49 UTC, yasserfaraazkhan commented on data/test-cases/suite/enterprise/user groups/MM-Test-Case-3.md
> +name: " Increase number of people that can be added to a group at once"
just a small formatting

2022-11-24 04:47 UTC, saturninoabril requested changes
Thanks @furqanmlk for adding test cases! LGTM. Left several comments but mostly formatting, typo, etc.

2022-11-24 04:47 UTC, saturninoabril commented on data/test-cases/suite/ad-ldap/MM-test-case-1.md
> +step 4: **userA** should be re-added to the team and the channe and **userB** should not get re-added to the team or the channel.
```suggestion
step 4: **userA** should be re-added to the team and the channel, and **userB** should not get re-added to the team or the channel.
```

2022-11-24 04:47 UTC, saturninoabril commented on data/test-cases/suite/enterprise/user groups/MM-Test-Case-1.md
> +name: "Add max height and overflow to Multiselect"
I initially thought that this title is a bit technical in nature and more on technical implementation details. Also, looking at the content (step/expectation), I feel like E2E is overkill and should've been caught in unit/component test. Thoughts?

2022-11-24 04:47 UTC, saturninoabril commented on data/test-cases/suite/enterprise/user groups/MM-Test-Case-2.md
> +10. Goto **ChannelA**.
```suggestion
10. Go to **ChannelA**.
```

2022-11-24 04:47 UTC, saturninoabril commented on data/test-cases/suite/enterprise/user groups/MM-Test-Case-2.md
> +12. Click group mention .
```suggestion
12. Click group mention.
```

2022-11-24 04:47 UTC, saturninoabril commented on data/test-cases/suite/enterprise/user groups/MM-Test-Case-2.md
> +- user groups popover should be displayed.
```suggestion
- User groups popover should be displayed.
```

2022-11-24 04:47 UTC, saturninoabril commented on data/test-cases/suite/enterprise/user groups/MM-Test-Case-4.md
> +on step 5: "test-group" should be visiblle in **Mention**.
```suggestion
on step 5: "test-group" should be visible in **Mention**.
```

2022-11-24 17:54 UTC, yasserfaraazkhan requested changes

2022-11-24 17:54 UTC, yasserfaraazkhan commented on data/test-cases/suite/ad-ldap/MM-test-case-1.md
> +1. Login as 2 LDAP users (userA and userB) in an LDAP group.
login as 2 in separate browsers ?

2022-11-24 17:54 UTC, yasserfaraazkhan commented on data/test-cases/suite/enterprise/user-groups/MM-Test-Case-1.md
> +2. Create 10 users.
can we add a sub test to use `/test cmd to create or should we manually invite users`

2022-11-24 17:54 UTC, yasserfaraazkhan commented on data/test-cases/suite/enterprise/user-groups/MM-Test-Case-2.md
> +name: "Add popover for user groups"
Kind of confused with title, `add popover`

should it be, `Verify pop-over appears ...`

2022-11-24 18:11 UTC, furqanmlk commented on data/test-cases/suite/ad-ldap/MM-test-case-1.md
> +1. Login as 2 LDAP users (userA and userB) in an LDAP group.
Log in as ```2 ldap users```

2022-11-24 18:11 UTC, furqanmlk commented on data/test-cases/suite/enterprise/user-groups/MM-Test-Case-1.md
> +2. Create 10 users.
For manual testing, it is up to the testers. Sometimes tester starts the server with ```--test-data``` or ```make test-data```.

2022-11-24 19:18 UTC, yasserfaraazkhan approved these changes
🌮

2022-11-25 02:25 UTC, saturninoabril commented on data/test-cases/suite/enterprise/user groups/MM-Test-Case-1.md
> +name: "Add max height and overflow to Multiselect"
I see, thanks for checking!

2022-11-25 02:26 UTC, saturninoabril commented on data/test-cases/suite/activity-and-insights/insights/MM-Test-Case-1.md
> +# (Optional)
Good point and I agree. I'll update the format as required.

2022-11-25 02:26 UTC, saturninoabril approved these changes
Thanks @furqanmlk!

2022-11-25 02:26 UTC, merged

2022-11-25 03:34 UTC, saturninoabril commented
@furqanmlk, test cases saved - https://github.com/mattermost/mattermost-test-management/commit/ebabb55c03550c3d1ff0cf184ac7e99c1bd08d9c. Note that I've manually changed the invalid Location value for it's not present in Zephyr. Currently, we're not saving anything to Zephyr whenever there's new custom field. Instead, it should be created and managed in the Zephyr's UI itself. I've created https://github.com/mattermost/mattermost-test-management/issues/25 to add validation.

Also, I changed folder name from "user-groups" to "User Groups" for consistency.