Feat(Edit Attachments): Add tests cases for edit attachments
mattermost/mattermost-test-management pull request #196
Opened 2024-12-05 16:31 UTC by yasserfaraazkhan

JIRA: https://mattermost.atlassian.net/browse/MM-62056

2024-12-05 19:17 UTC, marianunez commented on data/test-cases/channels/edited-post/1-Edit-Attachment.md
> +1. Navigate to a channel post.
This needs to be the users post to be able to see the `Edit` option so maybe for clarity, we add that it's the user's post or a step to do a post?

2024-12-05 19:17 UTC, marianunez commented on data/test-cases/channels/edited-post/1-Edit-Attachment.md
> +6. Verify a `Added today` label is shown.
Where does this label show? I don't recall seeing this in the designs

2024-12-05 19:17 UTC, marianunez commented on data/test-cases/channels/edited-post/2-Remove-Attachment.md
> +8. Verify a message `Attachment deleted` is shown.
Same as above, where would this show?

2024-12-05 19:17 UTC, marianunez commented on data/test-cases/channels/edited-post/3-Restore-Attachment.md
> +6. Verify the file public link shows a file not found error.
We want to make sure this is the case for admins as well.

2024-12-05 19:17 UTC, marianunez commented on data/test-cases/channels/edited-post/4-Download-Attachment.md
> +4. Download the attachment from the version other than the current one.
I believe we decided we are not going to allow to download the attachment of previous versions. Is that the case @harshilsharma63 ?

2024-12-05 19:54 UTC, yasserfaraazkhan commented on data/test-cases/channels/edited-post/1-Edit-Attachment.md
> +6. Verify a `Added today` label is shown.
@marianunez it was here. 
I think the new attachments will have the date/time on them

<img width="479" alt="image" src="https://github.com/user-attachments/assets/9fdcaeb3-717b-4f86-a2ba-784898f006a1">

2024-12-05 19:55 UTC, yasserfaraazkhan commented on data/test-cases/channels/edited-post/1-Edit-Attachment.md
> +6. Verify a `Added today` label is shown.
@marianunez 
would this be out of scope ? 

<img width="509" alt="image" src="https://github.com/user-attachments/assets/f25da60b-f7ef-45b9-b375-900236966342">

2024-12-06 06:42 UTC, harshilsharma63 requested changes

2024-12-06 06:42 UTC, harshilsharma63 commented on data/test-by-folder.json
> +      "Verify User can download from Edit History of a post",
This would not be allowed.  User will have to restore the historical version of the post to download the files.

2024-12-06 06:42 UTC, harshilsharma63 commented on data/test-by-folder.json
> +      "Verify User deleted files are not listed under channel files",
I'd also add "verify user deleted files are not downloadable by any user, including system admin, if they have a link for it.".

2024-12-06 06:42 UTC, harshilsharma63 commented on data/test-cases/channels/edited-post/1-Edit-Attachment.md
> +1. Navigate to a channel post.
So currently a system admin (maybe even a team admin? need to check for that) can edit someone else's post, but not see their edit history and thus, cannot restore an older version. Honoring the existing system, we should allow a system admin to add or remove post. I'll open up a thread in channel to confirm this.

2024-12-06 06:42 UTC, harshilsharma63 commented on data/test-cases/channels/edited-post/1-Edit-Attachment.md
> +6. Verify a `Added today` label is shown.
@yasserfaraazkhan yes the tooltip displayed in last screen is out of scope. We'll keep the existing tooltip on edit.

2024-12-06 06:42 UTC, harshilsharma63 commented on data/test-cases/channels/edited-post/3-Restore-Attachment.md
> +- The edited date of the post with attachments should be beyond the file retention and post retention days set.
I need to check if we delete old versions of a post if only an edit is beyond the data retention period while the latest post version is within.

2024-12-06 06:42 UTC, harshilsharma63 commented on data/test-cases/channels/edited-post/4-Download-Attachment.md
> +4. Download the attachment from the version other than the current one.
correct, we won't allow downloads from edit history

2024-12-06 13:00 UTC, marianunez commented on data/test-cases/channels/edited-post/1-Edit-Attachment.md
> +6. Verify a `Added today` label is shown.
@harshilsharma63 so you are extending the tooltip to say `Attachment added`?

2024-12-08 22:06 UTC, yasserfaraazkhan commented on data/test-cases/channels/edited-post/3-Restore-Attachment.md
> +6. Verify the file public link shows a file not found error.
done

2024-12-09 06:30 UTC, yasserfaraazkhan commented on data/test-by-folder.json
> +      "Verify User can download from Edit History of a post",
updated to "Verify User can download the files after restoring old post with attachments"

2024-12-09 06:35 UTC, yasserfaraazkhan commented on data/test-by-folder.json
> +      "Verify User deleted files are not listed under channel files",
done

2024-12-09 18:50 UTC, marianunez approved these changes
Thanks @yasserfaraazkhan!

2024-12-13 06:40 UTC, lindalumitchell approved these changes
Just a couple spelling nits. Looks good!

2024-12-13 06:40 UTC, lindalumitchell commented on data/test-cases/channels/edited-post/3-Restore-Attachment.md
> +2. Verify the user cannot see the post and files of an edit version beyoud data retention date.
```suggestion
2. Verify the user cannot see the post and files of an edit version beyond data retention date.
```

2024-12-13 06:40 UTC, lindalumitchell commented on data/test-cases/channels/edited-post/5-Channel-files.md
> +3. Copy the public link of the files and past it in the channel.
```suggestion
3. Copy the public link of the files and paste it in the channel.
```

2024-12-13 06:40 UTC, lindalumitchell commented on data/test-cases/channels/edited-post/3-Restore-Attachment.md
> +### Scenario 4: Verify user cannot see the post and file in the edit history if the data retension policy date has past.
```suggestion
### Scenario 4: Verify user cannot see the post and file in the edit history if the data retention policy date has past.
```

2024-12-13 14:59 UTC, merged