test(Sidebar) : Should not crash the app, when the rhs is opened and user goes to and back from system console
mattermost/mattermost-test-management pull request #23
Opened 2022-11-24 15:46 UTC by M-ZubairAhmed

#### Summary

#### Is the feature in stable branch or under review?
- [ ] Feature in stable branch (master, main)?
- [X] Feature still under review? If yes, list all related pull requests for reference.
  https://github.com/mattermost/mattermost-webapp/pull/11635

#### Test server

#### Test client

- [X] Browser
- [ ] Mobile App (version, OS)
- [X] Desktop App (version, OS)

2022-11-24 17:59 UTC, yasserfaraazkhan approved these changes
Thanks @M-ZubairAhmed ,
you can add your GitHub username in `authors:`

2022-11-24 17:59 UTC, yasserfaraazkhan commented on data/test-cases/channels/sidebar/MM-X1.md
> +authors: ""
authors: "[@M-ZubairAhmed](https://github.com/M-ZubairAhmed)"

2022-11-25 07:19 UTC, M-ZubairAhmed commented on data/test-cases/channels/sidebar/MM-X1.md
> +authors: ""
added

2022-11-25 07:19 UTC, M-ZubairAhmed commented on data/test-cases/channels/sidebar/MM-X1.md
> +- rhs
are these correct?

2022-11-25 07:20 UTC, M-ZubairAhmed commented on data/test-cases/channels/sidebar/MM-X1.md
> +---
is the test folder placement correct? Or do we want these to be somewhere else

2022-11-25 08:40 UTC, saturninoabril requested changes
Thanks Zubair! LGTM, except for few requests.

2022-11-25 08:40 UTC, saturninoabril commented on data/test-cases/channels/sidebar/MM-X1.md
> +---
I'm fine with this.

2022-11-25 08:40 UTC, saturninoabril commented on data/test-cases/channels/sidebar/MM-X1.md
> +folder: Channels
```suggestion
folder: Sidebar
```

Also for other test cases.

2022-11-25 08:40 UTC, saturninoabril commented on data/test-cases/channels/sidebar/MM-X1.md
> +- rhs
"se-prod" meant there's Selenium test in production which we no longer do. Same for other test cases.
```suggestion
labels:
- channel
- rhs
```

2022-11-25 08:40 UTC, saturninoabril commented on data/test-cases/channels/sidebar/MM-X2.md
> +authors: ""
Please add you GH handle. Same for other test cases.
```suggestion
authors: "@M-ZubairAhmed"
```

2022-11-25 10:01 UTC, M-ZubairAhmed commented on data/test-cases/channels/sidebar/MM-X1.md
> +folder: Channels
✅  Updated as per request/discussion

2022-11-25 10:01 UTC, M-ZubairAhmed commented on data/test-cases/channels/sidebar/MM-X1.md
> +- rhs
✅  Updated as per request/discussion

2022-11-25 10:01 UTC, M-ZubairAhmed commented on data/test-cases/channels/sidebar/MM-X2.md
> +authors: ""
✅  Updated as per request/discussion

2022-11-25 10:06 UTC, saturninoabril approved these changes
Thanks Zubair, LGTM.

2022-11-25 10:07 UTC, merged

2022-11-25 10:12 UTC, M-ZubairAhmed commented
@saturninoabril @yasserfaraazkhan can you let me know the test ids for these.

2022-11-25 10:14 UTC, saturninoabril commented
It's here - https://github.com/mattermost/mattermost-test-management/commit/8ca3dc3f680821bfa05400f9176f967f7b990f76