Mm 48573 2
mattermost/mattermost-test-management pull request #24
Opened 2022-11-24 16:46 UTC by yasserfaraazkhan

2022-11-24 16:58 UTC, yasserfaraazkhan commented
Hi @saturninoabril ,
I see this folder error when we run validate task,
I was the script passes it, I was wondering we need to throw error in there's mismatch

2022-11-25 04:41 UTC, saturninoabril requested changes
Thanks Yasser! See comment.

2022-11-25 04:41 UTC, saturninoabril commented on src/util/test_case.ts
> +  if (found) {
I think this will not work as expected. When you run `deno task validate-all` without changing any test case, this will throw an error which should not be the case.

I'd suggest to let [validate()](https://github.com/mattermost/mattermost-test-management/blob/main/src/util/validate.ts) complete the entire validation, log and track all errors found, and then let the caller decide whether to throw an error based on additional (new) return value (ex. `withError`), like for [validate](https://github.com/mattermost/mattermost-test-management/blob/main/src/validate.ts) (do the same for [save](https://github.com/mattermost/mattermost-test-management/blob/main/src/save.ts)):
```javascript
const { withError } = validate(args.all);
if (withError) {
  throw new Error('Not all entries are valid!');
}
```

2022-11-25 10:15 UTC, M-ZubairAhmed commented
/update-branch

2022-11-27 20:48 UTC, yasserfaraazkhan commented
@saturninoabril  
https://github.com/mattermost/mattermost-test-management/pull/24

covering the changes here, since these files have been merged,

2022-11-27 20:48 UTC, closed without merging