chore(new-Tests): Adding Pricing Modal testcase
mattermost/mattermost-test-management pull request #3
Opened 2022-10-14 21:02 UTC by yasserfaraazkhan

2022-10-18 16:53 UTC, neallred requested changes

2022-10-18 16:53 UTC, neallred commented on data/test-cases/cloud/pricing-modal/MM-Temp-test-1.md
> +- should currently be on a professional/entriprise license
This precondtion should seems like it should say "on cloud starter" license. I don't see the upgrade button if I upgrade 
 a workspace to cloud professional.

2022-10-18 16:53 UTC, neallred commented on data/test-cases/cloud/pricing-modal/MM-Temp-test-1.md
> +3: on entriprice pack, 'Try free**' button should be visible and disabled
Nit: for all tests, replace `entriprice` with `enterprise` and `Entriprice` with `Enterprise`.

2022-10-18 16:53 UTC, neallred commented on data/test-cases/cloud/pricing-modal/MM-Temp-test-1.md
> +3: on entriprice pack, 'Try free**' button should be visible and disabled
I think try free should be enabled. Can we remove the two asterisks from try free? I think the quoted text around it is sufficient.

2022-10-18 16:53 UTC, neallred commented on data/test-cases/cloud/pricing-modal/MM-Temp-test-2.md
> +
There is no professional trial, only enterprise trial. Do you mean requested enterprise trial, and the trial expired and the user was downgraded to starter?

2022-10-18 16:53 UTC, neallred commented on data/test-cases/cloud/pricing-modal/MM-Temp-test-3.md
> +- should have requested a professional trial before
The pre-condition should match the description of the test name. I *think* what is desired is that a user has downgraded to cloud starter.

2022-10-18 16:53 UTC, neallred commented on data/test-cases/cloud/pricing-modal/MM-Temp-test-3.md
> +name: "Cloud | With no previous trial and no current license Upgrade button for admin users on non trial licensed server"
This sounds like "installation is pre-trial on Cloud Starter" to me.

2022-10-18 16:53 UTC, neallred commented on data/test-cases/cloud/pricing-modal/MM-Temp-test-4.md
> +- should have requested a professional trial before
Update pre-condition.

2022-10-18 16:53 UTC, neallred commented on data/test-cases/cloud/pricing-modal/MM-Temp-test-4.md
> +3: Expect 'Upgrade' button should not be visible.
Tests 4-6 are exact duplicates of each other except for the name. Are they all needed? Or maybe some of the test description needs to be updated in them?

2022-11-27 20:50 UTC, yasserfaraazkhan commented
These have been outdated. Will restart again in near future.

2022-11-27 20:50 UTC, closed without merging