add code spell
mattermost/mattermost-test-management pull request #35
Opened 2022-12-12 18:36 UTC by yasserfaraazkhan

I usually make a lot of spelling mistakes. 

I bumped into code spell plugin, thought that will be a great addition to this repo.

Just trying out how this works

I'm trying both GitHub action and pre-commit hook, to see how it can be useful

<a href="https://gitpod.io/#https://github.com/mattermost/mattermost-test-management/pull/35"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2022-12-12 21:53 UTC, saturninoabril requested changes
@yasserfaraazkhan This is great and I love that you're adding this workflow! Thanks!

I did a quick pass and it's all good except for one possible ignore word.

2022-12-12 21:53 UTC, saturninoabril commented on data/test-by-folder.json
> -      "Add User — UserA & UserB (removed from team)",
Maybe UserA can be added to ignore list?

2022-12-13 09:03 UTC, yasserfaraazkhan commented on data/test-by-folder.json
> -      "Add User — UserA & UserB (removed from team)",
Ohh!! Right...
I'll add and push the change

2022-12-19 07:25 UTC, yasserfaraazkhan commented on data/test-by-folder.json
> -      "Add User — UserA & UserB (removed from team)",
@saturninoabril for some reason, just the `UserA` word is not being ignored.

I tried a lot, couldn't figure out is its something I'm missing or its the tool not able to pick the string **UserA** in the files. I'll try few more ways.

2023-01-03 10:16 UTC, saturninoabril commented on data/test-by-folder.json
> -      "Add User — UserA & UserB (removed from team)",
Thanks @yasserfaraazkhan! How about we replaced `UserA` to `"User A"`, same case for UserB?

2023-01-03 10:16 UTC, saturninoabril commented
@yasserfaraazkhan Let's get this merge soon as this is really useful. Again, thanks for adding this!

2023-01-04 19:02 UTC, yasserfaraazkhan commented on data/test-by-folder.json
> -      "Add User — UserA & UserB (removed from team)",
Thank you @saturninoabril , I did the above change.
I will need you help in verifying if the "user A" change won't impact _Folders.json_ . 
I've run all demo tasks locally to make sure commands run. (except Save and Sync)

2023-01-04 21:36 UTC, saturninoabril requested changes
Thanks Yasser! Last couple comments from me then this looks good to merge.

2023-01-04 21:36 UTC, saturninoabril commented on data/test-by-folder.json
> +      "Add User — User A & UserB (removed from team)",
Should it follow the same pattern in all places, like from "UserB" to "User B", from "ChannelA" to "Channel A", from "ChannelB" to "Channel B", etc? 
```suggestion
      "Add User — User A & User B (removed from team)",
```

2023-01-04 21:36 UTC, saturninoabril commented on data/test-by-folder.json
> +      "Add User — users & UserB (not on team)",
Should "users" be "User A" in this context? Same to be applied in other similar instances.

2023-01-04 21:36 UTC, saturninoabril commented on data/test-by-folder.json
> -      "Add User — UserA & UserB (removed from team)",
Great! Looks like it's safe with folders.json.

2023-01-05 10:13 UTC, saturninoabril commented on README.md
> +1. GitHub Actions runs codespell over your data/ folder will point out any common spelling mistakes in the Pull Request.
```suggestion
1. GitHub Actions runs [codespell](https://github.com/codespell-project/codespell) over your `data/` folder and will point out any common spelling mistakes in the Pull Request.
```

2023-01-05 10:14 UTC, saturninoabril approved these changes
Thanks @yasserfaraazkhan, so great to have this in place! Great work!

2023-01-05 15:04 UTC, merged

2023-01-05 15:44 UTC, neallred reviewed
Went through to verify changes. The biggest was a lot of lingering incorrect `UserA` -> `Users` changes we should go back through and fix since it will be really confusing to new readers of the documents here. Also noticed we may want an exception for `UserAccountControl`

2023-01-05 15:44 UTC, neallred commented on data/test-cases-manifest.json
> +            "name": "Add User — users & UserB (removed from team)",
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases-manifest.json
> +            "name": "Add User — users & UserB (not on team)",
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T2513.md
> +1. Log in as a users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T2513.md
> +4. users changes channel name in step 1A above by appending the word "hello" to the name
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T2515.md
> +3. User B "@mention" users in any channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T2515.md
> +users with with dot in username is returned in autocomplete suggestions
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T2515.md
> +3. User B "@mention" users in any channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T2515.md
> +users with with dash in username is returned in autocomplete suggestions
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T2515.md
> +3. User B "@mention" users in any channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T2515.md
> +users with with underscore in username is returned in autocomplete suggestions
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T3856.md
> +3. User B "@mention" users in any channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T3856.md
> +users with with dot in username is returned in autocomplete suggestions
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T3856.md
> +3. User B "@mention" users in any channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T3856.md
> +users with with dash in username is returned in autocomplete suggestions
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T3856.md
> +3. User B "@mention" users in any channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/autocomplete/with-elasticsearch/MM-T3856.md
> +users with with underscore in username is returned in autocomplete suggestions
Fix users. Also, there are too many `with`s . `with with underscore` -> `with underscore`

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/channel-settings/MM-T843.md
> +2. users click on reply icon on a post to open the RHS
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/channel-settings/MM-T843.md
> +4. User B removes users from the channel that is open in the RHS in 2)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/keyboard-shortcuts/MM-T1233.md
> +1\. As users make a post\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/keyboard-shortcuts/MM-T1233.md
> +4\. As users, press the UP arrow on your keyboard
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/left-sidebar/MM-T4609.md
> +a channel with 2 users - **users** and **User B**, where **User B** has already dismissed the unread and mention badge from being added to the channel (see MM-T4607)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/left-sidebar/MM-T4609.md
> +1. As  **users**, send a plain message (w/no mentions) in the test channel.
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/mark-as-unread/MM-T247.md
> +1. Have **users** mention **User B** in any Channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/mark-as-unread/MM-T247.md
> +1. Have **users** mention **User B** in another Channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/mark-as-unread/MM-T247.md
> +1. Have **users** mention **User B** in another Channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/mark-as-unread/MM-T247.md
> +1. Have **users** mention **User B** in another Channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/messaging/MM-T111.md
> +2. **users** flags a post in the private channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/messaging/MM-T111.md
> +3. **User B** mentions users in the private channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/messaging/MM-T111.md
> +4. **users** opens Saved Posts or Recent Mentions in RHS
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/messaging/MM-T111.md
> +5. The Saved post and the post mentioning **users** are shown in RHS
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/messaging/MM-T111.md
> +6. **User B** removes users from the same private channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/messaging/MM-T111.md
> +- **users** sees a notification that **User B** removed him from the channel
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/messaging/MM-T179.md
> +1\. As users copy the permalink of a post in any channel and paste it into another test channel mentioning User B in the post\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T423.md
> +1. users open a Direct Message channel with another account userB that is online (so you can see the DM and the other user's status in the LHS channel list)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T423.md
> +2. users switch to a different channel in the center
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T423.md
> +4. users observe userB's status indicator on that post
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T423.md
> +5. users click the member icon drop-down at the top of the channel so you can see the userB's status icon there as well
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T423.md
> +7. users watch all three status indicators; it will likely take about 30 to 60 seconds to change. Should all change to away at the same time (in the member icon drop-down this may also change where t
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T439.md
> +1. As the test user - users - disable Join/Leave messages in Account Settings ➜ Advanced ➜ Enable Join/Leave Messages
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T439.md
> +2. As users, join a team that User B is not on
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T439.md
> +3. As users, view a channel other than Town Square and ensure Town Square is not currently open and is not marked as unread
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T439.md
> +5. Once userB is on the team, as users, verify Town Square is not marked unread
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T439.md
> +6. As users, then switch channels to any channel other than Town Square
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/multi-team-and-dms/MM-T439.md
> +- users continues to observe Town Square in the LHS channel list as read and it does not become marked as unread
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4312.md
> +1. Create Public **Channel A** and **Channel B** and add users \*\*users in **C**hannelA \*\*and \*\*UsersB in \*\*\*\*\*\*C**hannelB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4314.md
> +1. Create Public **Channel A** and **Channel B** and add users \*\*users in **C**hannelA \*\*and \*\*UsersB in \*\*\*\*\*\*C**hannelB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4315.md
> +1. Create Public **Channel A** and **Channel B** and add users \*\*users in **C**hannelA \*\*and \*\*UsersB in \*\*\*\*\*\*C**hannelB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4317.md
> +1. Create Public **Channel A** and **Channel B** and add users \*\*users in **C**hannelA \*\*and \*\*UsersB in \*\*\*\*\*\*C**hannelB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4318.md
> +1. Create Public **Channel A** and **Channel B** and add users \*\*users in **C**hannelA \*\*and \*\*UsersB in \*\*\*\*\*\*C**hannelB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4321.md
> +1. Create Public **Channel A** and **Channel B** and add users \*\*users in **C**hannelA \*\*and \*\*UsersB in \*\*\*\*\*\*C**hannelB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4322.md
> +1. Create Public **Channel A** and Private **Channel B** and add users \*\*users in **C**hannelA \*\*and \*\*UsersB in \*\*\*\*\*\*C**hannelB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4323.md
> +3. Add **users** in these channels
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4324.md
> +1. Create **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4324.md
> +2. Create DM with **users** (i.e send direct message to **users)**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4324.md
> +5. Paste the permalink in the same **users** DM
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4324.md
> +6. Login as **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4324.md
> +7\. Permalink preview should be displayed to **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4326.md
> +2. Add \*\*users **and**\*\***userB** in both \*\*ChannelPB \*\*and **ChannelPR**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4326.md
> +3. Create DM with **users** (i.e send direct message to **users**)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4326.md
> +8. Login as **users** and navigate to **ChannelPB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4326.md
> +12. Login as **users** and navigate to **ChannelPB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4326.md
> +8\. Permalink preview will be displayed to **users**.\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4326.md
> +11.Permalink preview will be displayed to users and **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4326.md
> +12\. Permalink preview will be displayed to\*\* users\*\*
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4326.md
> +11.Permalink preview will be displayed to users and **users**\
There's also an opportunity to fix numbering here. It jumps from 8 to 11

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T4771.md
> +3. Create a Group message with **users**, **userB**, **userC**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T5089.md
> +1. Create Private **Channel A** and add users **UsersA**, **UsersB**, **UsersC** in this channel.
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T5091.md
> +1. Create Public **Channel A** and **Channel B** and add users \*\*UsersA in Channel A \*\*and **UsersB in C\*\*\*\*hannelB**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/permalink-preview/MM-T5091.md
> +1. Create Public **Channel A** and **Channel B** and add users \*\*UsersA in Channel A \*\*and **UsersB in C\*\*\*\*hannelB**
Also, looks like the markdown is incorrect for `C\*\*\*\*hannelB**`

2023-01-05 15:44 UTC, neallred commented on data/test-cases/channels/search/MM-T361.md
> +1\. Log in as a users and create a post that contains a hashtag such as #hello\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/integrations/MM-T660.md
> +1. As **users** create a new public channel or identify one that **User B** is not a member of yet
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/playbooks/MM-T4974.md
> +users, User B\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/playbooks/MM-T4974.md
> +1\. As users, make changes to checklist tasks (set assignee, check/uncheck, change due/date).\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/playbooks/MM-T4974.md
> +users, User B\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/playbooks/MM-T4974.md
> +1\. As users, post a status update to the run.\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/day-range/MM-T4968.md
> +3\. Add users **users, userB, userC**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/day-range/MM-T4968.md
> +3\. Add \*\*users \*\*in \*\*TeamA \*\*today\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/day-range/MM-T4968.md
> +5(1) . API should return **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/my-insights/MM-T4732.md
> +1\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/my-insights/MM-T4733.md
> +1\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/my-insights/MM-T4739.md
> +2\. Send **200 messages** to **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/my-insights/MM-T4740.md
> +1\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/my-insights/MM-T4741.md
> +1\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/my-insights/MM-T4816.md
> +2. Add users as a Guest
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/my-insights/MM-T4816.md
> +3. login as users (GUEST)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/my-insights/MM-T4816.md
> +2\. users should be added as Guest\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4754.md
> +9\. Create **users** and add to TeamA\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4754.md
> +10\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4755.md
> +10\. Create **users** and add to **TeamA**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4755.md
> +11\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4756.md
> +8\. Create **users** and add to **TeamA**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4756.md
> +9\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4757.md
> +8\. Create **users** and add to **TeamA**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4757.md
> +9\. Login as **users**.\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4758.md
> +12.Create** users** and add to** TeamA**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4758.md
> +13\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4759.md
> +6\. Create **users** and add to **TeamA**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4760.md
> +3\. Create **users** and add to **TeamA**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4760.md
> +4\. Login as **users**\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4761.md
> +6\. Create **users** and add to **TeamA**.\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4891.md
> +5. Make sure that users is not a part of Channel A
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4891.md
> +2. Create a Team and add users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/activity-and-insights/insights/team-insights/MM-T4891.md
> +6. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/ad-ldap/MM-T2697.md
> +   (&(objectCategory=Person)(!(User AccountControl:
We probably need to make an exception for `UserAccountControl` as well since in this case that is an actual known entity we are trying to describe. If you can't get codespell to respect that exception, it's probably ok, but would be better to omit it from the spell correction list if possible.

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/ad-ldap/MM-T5307.md
> +1. Login as two LDAP users (users and userB) in an LDAP group.
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/ad-ldap/MM-T5307.md
> +4. Go to **System Console** > **Users**, go to **users**, and from the drop down menu select **Reset group-defaulted teams and channels**.
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/ad-ldap/MM-T5307.md
> +step 2: the users should get added to the team and then channel.step 4: **users** should be re-added to the team and the channel and **userB** should not get re-added to the team or the channel.
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4658.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4659.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4660.md
> +3. Add **users** in **GroupA** and **GroupC**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4661.md
> +1. Login as **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4662.md
> +1. Login as **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4663.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4664.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4665.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4666.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4667.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4668.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4669.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4669.md
> +2. Create GroupA and add users and User B 
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4669.md
> +3. Create Channel A and add users and User B
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4669.md
> +4. users and User B should get notified
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4670.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4671.md
> +1. Login as users
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4678.md
> +2. Add **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4678.md
> +6. Type **users** in Name field
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4678.md
> +7. Type \*\*users \*\*in mention field
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4678.md
> +9. Select **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4678.md
> +- Add **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/custom-groups/MM-T4678.md
> +- Select **users**
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/ldap-group-sync/MM-T2611.md
> +User filter to filter out deactivated users (such as (&(objectClass=person)(!(cn=Test.\*))(!(User AccountControl:1.2.840.113556.1.4.803:=2)))\
Ditto `UserAccountControl`

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T1573.md
> +1. On mobile app, view channelA (we'll call you users)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T1573.md
> +4. Ensure users is in that channelB, or add them to it
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T1573.md
> +5. While viewing mobile app as users, have userB post `@all` in that channelB twice in quick succession
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T1573.md
> +- users sees two in-app notifications at the top of the screen, one after the other
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T3314.md
> +1. Have users @mention User B to trigger a desktop notification containing one or more emojis
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T506.md
> +2. Log in to the same server with two test users (users and User B)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T506.md
> +5. As users, send an at-mention to User B and include a link to a channel (e.g. `This is a message in \~off-topic channel for @userB`)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T530.md
> +1. As users, tap the three-dot menu in the top right of your screen
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T530.md
> +5. As User B, send users a DM
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T530.md
> +6. As users, tap the push notification
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T530.md
> +- users is taken to the DM message from User B
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T554.md
> +1. As **users** and with "Trigger notifications on messages in reply threads that I start or participate in" selected in Account settings, reply to a parent post made by a different account.
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T554.md
> +3. As **users**, tap the push notification when it is received.
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/notifications/MM-T554.md
> +- **users** should receive a mention notification on the comment made by the second test account
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/sign-in-authentication/MM-T415.md
> +- users sees
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/system-console/compliance/custom-terms-of-service/MM-T1191.md
> +9. Ordinary user, users, click on "I Agree" on Terms of Service page you are viewing (with the original text)
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/system-console/compliance/custom-terms-of-service/MM-T1191.md
> +10. users then sees the updated TOS from step 8
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/system-console/compliance/custom-terms-of-service/MM-T1191.md
> +- After agreeing to the original TOS and ALSO the updated TOS, users is directed to the team
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/system-console/site-configuration/users-and-teams/MM-T1058.md
> +a. users\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/system-console/site-configuration/users-and-teams/MM-T1061.md
> +a. users\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/system-console/site-configuration/users-and-teams/MM-T1064.md
> +a. users\
Fix users

2023-01-05 15:44 UTC, neallred commented on data/test-cases/suite/system-console/site-configuration/users-and-teams/MM-T1065.md
> +a. users\
Fix users

2023-01-05 15:54 UTC, yasserfaraazkhan commented
@neallred Thank you Nathan, I'll quickly follow these up with a PR.
are you suggesting to skip the word 'UserAccountControl'?

2023-01-06 07:50 UTC, yasserfaraazkhan commented on data/test-cases/channels/channel-settings/MM-T843.md
> +3. users leaves RHS open and navigates to another channel in the center panel
done

2023-01-06 07:54 UTC, yasserfaraazkhan commented on data/test-cases/suite/system-console/compliance/custom-terms-of-service/MM-T1191.md
> +- After agreeing to the original TOS and ALSO the updated TOS, users is directed to the team
done

2023-01-06 08:49 UTC, saturninoabril commented on data/test-by-folder.json
> +      "Add User — users & UserB (not on team)",
Hello @yasserfaraazkhan, I've seen this was already merged. However, there were many instance of "UserA" changed to "users". Could you make sure to get back to all of it and correctly changed as "User A".

Thanks!

2023-01-06 08:53 UTC, yasserfaraazkhan commented on data/test-cases/channels/left-sidebar/MM-T4609.md
> +a channel with 2 users - **users** and **User B**, where **User B** has already dismissed the unread and mention badge from being added to the channel (see MM-T4607)
done

2023-01-06 08:54 UTC, yasserfaraazkhan commented on data/test-cases/channels/mark-as-unread/MM-T247.md
> +1. Have **users** mention **User B** in any Channel
done

2023-01-06 09:59 UTC, yasserfaraazkhan commented on data/test-cases/suite/ad-ldap/MM-T2697.md
> +   (&(objectCategory=Person)(!(User AccountControl:
done