Simple integration of Silver Bullet via gitpod
mattermost/mattermost-test-management pull request #4
Opened 2022-10-27 09:18 UTC by zefhemel

2022-10-27 13:37 UTC, saturninoabril requested changes
This is so cool! Thanks @zefhemel!

I played around and so good! I just noticed one thing -- image preview is not loading in markdown.
<img width="824" alt="Screen Shot 2022-10-27 at 9 13 20 PM" src="https://user-images.githubusercontent.com/5334504/198299422-b32f66d3-c13f-485f-9b02-cbfccec10d20.png">

2022-10-27 13:37 UTC, saturninoabril commented on deno.jsonc
> +    "silverbullet": "deno run -A --unstable https://get.silverbullet.md -p 3333 data/test-cases"
Can we move the page-path to `data`? Though we can make exceptions at `data/test-cases` for files/pages being created by `silverbullet`, I'd rather keep it intact to have the exact folders and files with Zephyr. Currently, it's having conflict when running `deno task sync | validate | save`.

2022-10-27 13:37 UTC, saturninoabril commented on data/test-cases/Cypress status.md
> +<!-- #query page render [[template/cypress]] where status = "Active" and cypress = "Evaluating" limit 50 -->
On initial opening of Gitpod, this file is showing some diff. Maybe add some sort expression?
```suggestion
<!-- #query page render [[template/cypress]] where status = "Active" and cypress = "Evaluating" order by id asc limit 50 -->
```

Same happened with "Test Cases" page.

2022-10-27 13:37 UTC, saturninoabril commented on .gitpod.yml
> +    visibility: public
> For some reason the browser doesn't auto open to Silver Bullet, but when you click on "Ports" at the bottom right you can open it from there.

Happened to me too and it's being block by Chrome which is fine with me. Maybe because of using port 3333? (just guessing)

NS(me): I'll document the behavior somewhere in the docs.

2022-10-28 08:01 UTC, m1lt0n commented on deno.jsonc
> +    "silverbullet": "deno run -A --unstable https://get.silverbullet.md -p 3333 data/test-cases"
+1 on this

2022-11-09 08:17 UTC, zefhemel commented on deno.jsonc
> +    "silverbullet": "deno run -A --unstable https://get.silverbullet.md -p 3333 data/test-cases"
Done

2022-11-09 08:19 UTC, zefhemel commented on deno.jsonc
> +      "include": ["src/", "data/test-cases"]
Had to limit to just test-cases, because `deno fmt` adds all types of newlines to e.g. templates which messes up the lay-out.

2022-11-09 09:25 UTC, m1lt0n approved these changes

2022-11-09 09:28 UTC, m1lt0n commented
@zefhemel just out of pure curiosity regarding the committed pages with queries, would it make sense for those to have just the query without results in the repo, since the outcome is dynamic? So, to be "<!-- query ... >{nothing}<! -- >" instead of having results in it commited (nitpicking probably, but just curious about it)?

2022-11-09 10:54 UTC, saturninoabril commented
I'm getting error `error: Module not found "https://get.silverbullet.md/".` using the old and new Gitpod workspace. WIll try again with the updated branch.
<img width="817" alt="Screen Shot 2022-11-09 at 6 49 00 PM" src="https://user-images.githubusercontent.com/5334504/200811876-565bf557-4254-42f9-bbb7-3ada0621c281.png">

2022-11-09 12:53 UTC, saturninoabril requested changes

2022-11-09 12:53 UTC, saturninoabril commented on .gitignore
> +data/data.db*
Not requesting for change but I wonder if checking this in (~2mb currently) would be more practical rather than waiting for files to be indexed by silverbullet.

2022-11-09 12:53 UTC, saturninoabril commented on deno.jsonc
> +      "include": ["src/", "data/test-cases"]
Some of the json files in `data` folder are to be formatted by `deno fmt`. Maybe exclude md files generated by silverbullet?
```json
"include": ["src/", "data/"],
"exclude": [
  "data/template/",
  "data/Cypress status.md",
  "data/Mobile v2.md",
  "data/Test Cases.md"
]
```

2022-11-09 12:53 UTC, saturninoabril commented on data/Test Cases.md
> +<!-- #query page render [[template/test-case]] where status = "Active" order by last_updated desc limit 10 -->
There are test cases with same `last_updated`. With that, it may cause inconsistent ordering in the result. Since silverbullet is not yet supporting nested ordering like `... order by last_updated desc, id desc ...`, maybe just change this to `order by id desc` then section header to `Recently added`? Or I could change in separate PR the `last_updated` to have precision down to milliseconds instead of seconds currently.

2022-11-09 13:16 UTC, saturninoabril commented on data/Test Cases.md
> +<!-- #query page render [[template/test-case]] where status = "Active" order by last_updated desc limit 10 -->
Or the one as suggested here - https://github.com/mattermost/mattermost-test-management/pull/4#issuecomment-1308463460

2022-11-09 15:46 UTC, zefhemel commented on .gitignore
> +data/data.db*
It would 100% override this file for every minor change in any of the test cases probably, so 🤷🏻

2022-11-09 15:49 UTC, zefhemel commented
> @zefhemel just out of pure curiosity regarding the committed pages with queries, would it make sense for those to have just the query without results in the repo, since the outcome is dynamic? So, to be "<!-- query ... >{nothing}<! -- >" instead of having results in it commited (nitpicking probably, but just curious about it)?

This is a good question not specific to this PR. In practical terms this is tricky, because you basically have to remove the content (or have a command for this) before every commit, and then bring it back so you see it for your own use. Perhaps there should be a `silverbullet clean` command or similar that does this that you can use in a pre-commit hook or something?

2022-11-11 03:51 UTC, saturninoabril commented on .gitignore
> +data/data.db*
I see, that's the drawback. Then I'm good as is.

2022-11-11 03:58 UTC, saturninoabril approved these changes
Thanks Zef! I don't mean to block this PR for long and I'd love to have this soon. It's busy week :) but let me know if you're working on my last comments. Otherwise, I could merge this and I'll take care some follow up change.
Thanks and happy to see silverbullet here!

2022-11-15 07:52 UTC, merged