test(delete global draft): adding new test case for deleting global drafts
mattermost/mattermost-test-management pull request #40
Opened 2022-12-29 20:34 UTC by jgilliam17

#### Summary

Adding a new test case for global drafts, testing delete from global drafts and cancel delete
#### Is the feature in stable branch or under review?
- [] Feature in stable branch (master, main)?
- [] Feature still under review? If yes, list all related pull requests for reference.

#### Test server

#### Test client

- [] Browser
- [] Mobile App (version, OS)
- [] Desktop App (version, OS)

2022-12-29 22:57 UTC, mattermost-quality requested changes
Thanks Jelena!

2022-12-29 22:57 UTC, mattermost-quality commented on data/test-cases/channels/global-drafts/delete.md
> +Draft can be deleted
nit: add space so that it's [not rendered in the same line](https://github.com/mattermost/mattermost-test-management/blob/9a458d075692e81a00169742e23bf0740a050d24/data/test-cases/channels/global-drafts/delete.md)

<img width="345" alt="Screenshot 2022-12-30 at 6 55 57 AM" src="https://user-images.githubusercontent.com/120147205/210018896-99747df5-c09b-430e-951e-da9968abfa40.png">

```suggestion
**Step 1**

Draft can be deleted
```

2022-12-29 22:57 UTC, mattermost-quality commented on data/test-cases/channels/global-drafts/delete.md
> +User can cancel draft deletion
```suggestion
**Step 2**

User can cancel draft deletion
```

2022-12-29 23:17 UTC, saturninoabril requested changes
Thanks Jelena! Please see comment/suggestions.

2022-12-29 23:17 UTC, saturninoabril commented on data/test-cases/channels/global-drafts/delete.md
> +Draft can be deleted
nit: add space to [not render in separate line](https://github.com/mattermost/mattermost-test-management/blob/9a458d075692e81a00169742e23bf0740a050d24/data/test-cases/channels/global-drafts/delete.md)
<img width="345" alt="Screenshot 2022-12-30 at 6 55 57 AM" src="https://user-images.githubusercontent.com/5334504/210020106-426e82a8-5fbb-4e50-8848-14c760c7ca8c.png">

```suggestion
**Step 1**

Draft can be deleted
```

2022-12-29 23:17 UTC, saturninoabril commented on data/test-cases/channels/global-drafts/delete.md
> +User can cancel draft deletion
```suggestion
**Step 2**

User can cancel draft deletion
```

2022-12-29 23:30 UTC, saturninoabril approved these changes
Thanks Jelena!

2022-12-29 23:46 UTC, saturninoabril commented
Merging this now.

2022-12-29 23:46 UTC, merged

2022-12-30 00:00 UTC, saturninoabril commented
New test case saved as [MM-T5366](https://github.com/mattermost/mattermost-test-management/commit/049ab86350490d30057e1673887f429f82ff6247#diff-5ee05eb657f992160f15d9f6fb5b5122c072dc704707a7309df76cb6030cb55f).