new tests for marking channel as unread
mattermost/mattermost-test-management pull request #5
Opened 2022-11-04 16:21 UTC by jgilliam17

#### Summary

Adding new test cases for mark channel as unread
#### Ticket Link

2022-11-04 22:08 UTC, saturninoabril requested changes
Thanks @jgilliam17! Really appreciate for you going ahead with this new process! Please see comments.

For other reviewer, I believe this is still not on master -- on going review at https://github.com/mattermost/mattermost-webapp/pull/10755. You may use the test server on that PR.

2022-11-04 22:08 UTC, saturninoabril commented on data/test-cases/channels/mark-as-unread/mark-channel-unread1.md
> +    1. Verify the New Messages line should appear above the last post (post3)
In preview mode, the indented statement for verify is showing either `1.` in editor or `i.` in GitHub (see screenshot).
<img width="567" alt="Screen Shot 2022-11-05 at 5 58 20 AM" src="https://user-images.githubusercontent.com/5334504/200081344-e5291837-d778-4783-a83d-8d29ac8300fd.png">

How about using the bullet point (either below)?

<img width="531" alt="Screen Shot 2022-11-05 at 5 59 37 AM" src="https://user-images.githubusercontent.com/5334504/200081368-820056cc-1636-4c8a-bae5-8b9f20eedca5.png">

<img width="574" alt="Screen Shot 2022-11-05 at 5 59 17 AM" src="https://user-images.githubusercontent.com/5334504/200081319-3b03c5e8-927f-454c-bf5e-4f9799e79c29.png">

2022-11-04 22:08 UTC, saturninoabril commented on data/test-cases/channels/mark-as-unread/mark-channel-unread1.md
> +When marking the channels as unread, the channel should show as unread on the sidebar. When opening a channel that was marked as unread manuually, the New Messages line should appear above the last p
```suggestion
When marking the channels as unread, the channel should show as unread on the sidebar. When opening a channel that was marked as unread manually, the New Messages line should appear above the last post in the channel
```

2022-11-04 22:08 UTC, saturninoabril commented on data/test-cases/channels/mark-as-unread/mark-channel-unread2.md
> +name: "The latest post should appear unread after marking the channel as unread with alt-left-click on channel sidebar item"
Please indicate the key when using Mac. It would be `option` key, right?

2022-11-04 23:24 UTC, saturninoabril commented
Also, we're following conventional commits - https://www.conventionalcommits.org/en/v1.0.0/. Since we're doing "squash and merge", the commit message takes the PR title. With that, I'm recommending the following format for test cases PR:
```
test(feature): general description of tests
```

And so, please change to something like:
```
test(mark as unread): latest post should appear unread after marking the channel as unread in RHS via menu option or shortcut key
```

2022-11-07 20:48 UTC, jgilliam17 commented on data/test-cases/channels/mark-as-unread/mark-channel-unread2.md
> +name: "The latest post should appear unread after marking the channel as unread with alt-left-click on channel sidebar item"
Great point. Fixed.

2022-11-07 21:00 UTC, jgilliam17 commented
Thanks @saturninoabril 
I've made all the changes as requested. Please take another look 🙂

2022-11-07 21:03 UTC, saturninoabril commented
Thanks @jgilliam17! LGTM.

2022-11-07 21:03 UTC, saturninoabril approved these changes

2022-11-07 21:33 UTC, saturninoabril commented
I'm merging this now.

2022-11-07 21:35 UTC, merged