test(MM-48845) : Test cases for channel moveTo category sub menu options
mattermost/mattermost-test-management pull request #53
Opened 2023-01-18 08:27 UTC by M-ZubairAhmed

#### Summary
Adds test cases for channel move to menu options under

#### Is the feature in stable branch or under review?
- [X] Feature in stable branch (master, main)?
- [ ] Feature still under review? If yes, list all related pull requests for reference.

#### Test server
https://mattermost.atlassian.net/browse/MM-48845

#### Test client

- [X] Browser
- [] Mobile App (version, OS)
- [X] Desktop App (version, OS)

2023-01-18 08:29 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +**Step 2**
These are test cases like MM-XX_1, MM-XX_2

2023-01-19 07:31 UTC, lindy65 requested changes
Thanks @M-ZubairAhmed - a few grammatical updates

2023-01-19 07:31 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there is at least two channels are present in the "Channels" category
Should be "Make sure there are_"

2023-01-19 07:31 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there is at least two DMs are present in the "Direct Messages" category
Should be "Make sure there are_"...

2023-01-19 07:31 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there is at least a channel, DM and GM are present
Make sure there are at least a channel, DM and GM present

2023-01-19 07:31 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on either of channels menu option
Click on either of the channels menu options

2023-01-20 06:56 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there is at least two channels are present in the "Channels" category
done

2023-01-20 06:56 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there is at least two DMs are present in the "Direct Messages" category
done

2023-01-20 06:57 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on either of channels menu option
done

2023-01-20 06:57 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there is at least a channel, DM and GM are present
done

2023-01-20 11:17 UTC, lindy65 requested changes
Thanks @M-ZubairAhmed - a few grammatical suggestions

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Go to the clicked channel
Is the "clicked" channel the one that was selected in line 39?  If so, perhaps this step would read better as "Go to the previously selected channel"?

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on a DM channel menu option
"Click on any DM channel menu option"

To match the "any" in line 39

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Go to the clicked DM channel
Perhaps change to "Go to the previously selected DM channel"

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on a GM channel menu option
"Click on any GM channel menu option"

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Go to the clicked GM channel
"Go to the previously selected GM channel"

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there are at least two channels are present in the "Channels" category
delete "are" before "present in_"...

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on either of channels menu option
"Click on either of the channel's menu options"

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there are at least two DMs are present in the "Direct Messages" category
Delete "are" before "present in_"...

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on either of DMs menu option
"Click on either of the DM's menu options"

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on either of the channels menu options
Click on any one of the channel's menu options

2023-01-20 11:17 UTC, lindy65 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there are at least a channel, DM and GM present
Make sure there is a channel, DM and GM present

2023-01-23 11:40 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Go to the clicked channel
done

2023-01-23 11:40 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on a DM channel menu option
done

2023-01-23 11:41 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on a GM channel menu option
done

2023-01-23 11:42 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there are at least two channels are present in the "Channels" category
done

2023-01-23 11:42 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on either of channels menu option
done

2023-01-23 11:43 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there are at least a channel, DM and GM present
done

2023-01-23 11:43 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on either of the channels menu options
done

2023-01-23 11:43 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Click on either of DMs menu option
done

2023-01-23 11:43 UTC, M-ZubairAhmed commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Make sure there are at least two DMs are present in the "Direct Messages" category
done

2023-01-23 17:37 UTC, lindy65 approved these changes
Thanks @M-ZubairAhmed - looks good to me 👍

2023-01-24 05:30 UTC, jgilliam17 reviewed
Thanks @M-ZubairAhmed 
I added suggestions for each test step to include title and Expected field.
Feel free to edit the text if needed.
Additionally, I noted in expected a common sub-menu option "New Category" was present in all tested scenarios.

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +
```suggestion

**Expected**

For multi-select group of channels, "Move to " sub menu options are  "Favorites" category, followed by "Channels" category and option to create and move to "New Category". "Direct Messages" should not be available.

---
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +
```suggestion

**Expected**

For multi-select DM group, "Move to " sub menu options are  "Favorites" category, followed by "Direct Messages" category and option to create and move to "New Category". "Channels" category is not available.

---
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Channels" and "Direct Messages" categories are not displayed
```suggestion
1. Verify that "Channels" and "Direct Messages" categories are not displayed

**Expected**

For multi-select group consisting of DMs, GMs and channels,  "Move to " sub menu options are  "Favorites" category, followed by created custom category and  option to create and move to "New Category". "Channels" and "Direct Messages" categories are not available.

---
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +
```suggestion

"Move to" sub menu options for multi-select DM group

```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by created custom category and "Channels" categories are displayed
```suggestion
1. Verify that "Favorites" category, followed by created custom category and "Channels" categories are displayed
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by created custom category and "Channels" categories are displayed
```suggestion
1. Verify that "Favorites" category, followed by created custom category and "Channels" categories are displayed
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by created custom category and "Direct Messages" categories are displayed
```suggestion
1. Verify that "Favorites" category, followed by created custom category and "Direct Messages" categories are displayed
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by created custom category and "Direct Messages" categories are displayed
```suggestion
1. Verify that "Favorites" category, followed by created custom category and "Direct Messages" categories are displayed
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by created custom category and "Direct Messages" categories are displayed
```suggestion
1. Verify that "Favorites" category, followed by created custom category and "Direct Messages" categories are displayed
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by created custom category and "Direct Messages" categories are displayed
```suggestion
1. Verify that "Favorites" category, followed by created custom category and "Direct Messages" categories are displayed
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by "Channels" categories are displayed and "Direct Messages" category is not displayed
```suggestion
1. Verify that "Favorites" category, followed by "Channels" categories are displayed and "Direct Messages" category is not displayed
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by "Direct Messages" categories are displayed and "Channels" category is not displayed
```suggestion
1. Verify that "Favorites" category, followed by "Direct Messages" categories are displayed and "Channels" category is not displayed
```

2023-01-24 05:30 UTC, jgilliam17 commented on data/test-cases/channels/channel-menu/MM-XXX.md
> +1. Verify that "Favorite" category, followed by created custom category category is displayed
```suggestion
1. Verify that "Favorites" category, followed by created custom category category is displayed
```

2023-02-10 21:17 UTC, saturninoabril commented
Thanks @jgilliam17 for the review!

2023-02-10 21:17 UTC, saturninoabril approved these changes
Thanks @M-ZubairAhmed, LGTM!

2023-02-10 21:19 UTC, merged

2023-02-10 21:26 UTC, saturninoabril commented
Test case saved as MM-T5385