test(global drafts-onboarding-tour-tip): New test for Global Drafts onboarding
mattermost/mattermost-test-management pull request #55
Opened 2023-01-20 18:01 UTC by jgilliam17

#### Summary

Adding new test for global Drafts onboarding tour tip
Jira ticket: https://mattermost.atlassian.net/browse/MM-49179
#### Is the feature in stable branch or under review?
- [] Feature in stable branch (master, main)?
- [] Feature still under review? If yes, list all related pull requests for reference.

#### Test server

#### Test client

- [] Browser
- [] Mobile App (version, OS)
- [] Desktop App (version, OS)

2023-01-20 18:13 UTC, jgilliam17 commented
Originally I had step 2 incorporated into step 1, and then decided to split it out into a separate step.
Thoughts?
I'm ok with either approach.

2023-01-21 00:16 UTC, saturninoabril requested changes
Thanks Jelena! LGTM, except for couple of request.

2023-01-21 00:16 UTC, saturninoabril commented on data/test-cases/channels/global-drafts/Global-Drafts-Onboarding-Tourtip
> +   2. Verify draft created in step 2 is present
I'd prefer to merge this step 2 to 1 so some steps are not repeated as it's likely the same when doing manual and automated tests.

2023-01-21 00:24 UTC, jgilliam17 commented on data/test-cases/channels/global-drafts/Global-Drafts-Onboarding-Tourtip
> +---
Oh, good catch. Done

2023-01-21 00:24 UTC, jgilliam17 commented on data/test-cases/channels/global-drafts/Global-Drafts-Onboarding-Tourtip
> +   2. Verify draft created in step 2 is present
Changed. Can you take another look? Thanks.

2023-01-21 00:38 UTC, mattermost-quality approved these changes
Thanks Jelena, looks good to me!

2023-01-21 00:38 UTC, mattermost-quality commented on data/test-cases/channels/global-drafts/Global-Drafts-Onboarding-Tourtip.md
> +3. Click on Not Now button on the tour
nit: for consistency
```suggestion
3. Click on "Not Now" button on the tour
```

2023-01-21 00:41 UTC, saturninoabril commented
(Oh no... it should not be the bot account. My bad).

2023-01-21 00:41 UTC, saturninoabril approved these changes
LGTM, thanks Jelena!

2023-01-21 00:42 UTC, merged

2023-01-21 00:50 UTC, saturninoabril commented
Test created as [MM-T5378](https://github.com/mattermost/mattermost-test-management/blob/main/data/test-cases/channels/global-drafts/MM-T5378.md).