test(MM-T5360): Should open the invite screen
mattermost/mattermost-test-management pull request #57
Opened 2023-01-20 21:09 UTC by stevemudie

#### Summary

This fills in the previously missing test steps for the placeholder [MM-T5360](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T5360) regarding https://github.com/mattermost/mattermost-mobile/pull/6877

Ticket ➜ [MM-42835](https://mattermost.atlassian.net/browse/MM-42835)
[Figma design](https://www.figma.com/file/mvJXgiirM4ucPW8bHAvM4G/MM-39720-Invite-People?node-id=276%3A230414)
[Figma prototype]([Figma prototype](https://www.figma.com/proto/mvJXgiirM4ucPW8bHAvM4G/MM-39720-Invite-People?page-id=117%3A212251&node-id=206%3A218607&viewport=478%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=206%3A218607&show-proto-sidebar=1))

2023-01-21 00:35 UTC, saturninoabril requested changes
Thanks Steve! Please see comments.

2023-01-21 00:35 UTC, saturninoabril commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +team_ownership: Growth
This accepts multiple values, and so should be:
```suggestion
team_ownership:
- Growth
```

2023-01-21 00:35 UTC, saturninoabril commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
>  status: Draft
I just can't highlight the specific line but for the "name" field, please follow the title convention for Mobile V2 as recommended by Joseph. Could be:
```diff
- name: "Should open the invite screen"
+ name: "Mobile V2: Invite - Should open the invite screen"
```

Also, change to active.
```suggestion
status: Active
```

2023-01-21 00:35 UTC, saturninoabril commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +• The invite menu appears at the bottom of the screen
Since the test is about opening the Invite Screen, should it include the condition on when to open or not considering the permission of the user and invite link being enabled? I've looked at the other draft test cases but it seemed to be better to include here.

2023-01-23 18:21 UTC, julmondragon commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +2. In the menu that pops up from the bottom of the screen tap 'Invite people to the team'
Please be aware that this workflow will be updated once https://github.com/mattermost/mattermost-mobile/pull/6877 is merged, to require an additional step:

`3. In the Invite screen that pops up from the bottom of the screen tap 'Share link' button`

2023-01-24 20:30 UTC, marianunez commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +name: "Mobile V2: Invite - Should open the invite screen"
Should we update this to Invite by Link and then aadd another test to cover the case of invite by email ?

2023-01-24 21:51 UTC, stevemudie commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +name: "Mobile V2: Invite - Should open the invite screen"
[MM-T5362](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T5362) will cover invite by email (once it's written)

2023-01-24 22:18 UTC, stevemudie commented
@saturninoabril @julmondragon @marianunez Thank you for your input thus far!

I did an extensive rewrite with the latest commit to merge what is expected as the user moves through the test directly into the test steps.

This puts the test in line with an approach we discussed in our weekly [QA meeting earlier today](https://community.mattermost.com/core/pl/7bi5hptpi78tzktbh43hq44tio) and helps to address comments made thus far here in the PR as well as keeping the scope of this specific test contained.

I also added text for the `Objective` and `Precondition` fields that appear in the first tab when you open a test case over on Zephyr Scale that helps to set the stage for the test at hand.

@saturninoabril **Side note**: Perhaps those should be incorporated into [TEST_CASE_TEMPLATE.md](https://github.com/mattermost/mattermost-test-management/blob/main/data/TEST_CASE_TEMPLATE.md) to encourage their use?

More tests are on the way as outlined in this screenshot to cover all of the aspects of the invitation workflow.

<img width="600" alt="Mobile V2 invitation test list" src="https://user-images.githubusercontent.com/7083912/214432317-6f1214ff-91c1-4649-bc66-6231669c4ad4.png">

2023-01-25 05:29 UTC, lindalumitchell approved these changes

2023-01-25 05:29 UTC, lindalumitchell commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +    • Everything works as expected to that point
```suggestion
    • Invite screen opens as described in step 3
```

2023-01-25 05:29 UTC, lindalumitchell commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +    • Everything works as expected to that point
I might more specifically just echo what the test title is here. This looks great though! Just a minor suggestion; approving. :)

2023-01-25 15:39 UTC, stevemudie commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +    • Everything works as expected to that point
Great idea @lindalumitchell! Done!

2023-01-25 18:11 UTC, stevemudie commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +• The invite menu appears at the bottom of the screen
The rewrite should address this but let me know if you have other ideas on how should bake what you mentioned into the steps.

2023-01-25 20:34 UTC, jgilliam17 approved these changes
Thanks @stevemudie 
LGTM

2023-01-26 09:52 UTC, saturninoabril commented
> Side note: Perhaps those should be incorporated into [TEST_CASE_TEMPLATE.md](https://github.com/mattermost/mattermost-test-management/blob/main/data/TEST_CASE_TEMPLATE.md) to encourage their use?

Sounds good to me Steve. Thanks for the input! I'll take a look.

2023-01-26 10:23 UTC, saturninoabril requested changes
Thanks Steve. Last requests and I'm all good.

2023-01-26 10:23 UTC, saturninoabril commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +2. Tapping the + sign in the top right corner of the mobile app opens the invite menu at the bottom of the screen
Is it "invite menu" or "team menu"?
```suggestion
2. Tapping the + sign in the top right corner of the mobile app opens the team menu at the bottom of the screen
```

2023-01-26 10:23 UTC, saturninoabril commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +name: "Mobile V2: Invite - Should open the invite screen"
I agree with Maria. Since the steps extends up to "Share link", maybe this test case should validate the link to be shared and not just opening the Invite screen?
```suggestion
name: "Mobile V2: Invite - Share link"
```

2023-01-26 10:23 UTC, saturninoabril commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +    • Tapping the 'Share link' button in the top right corner dismisses the screen and opens up the system sharing options at the bottom of the screen
Can we add validation after tapping the "Share link" since it's likely the last UI flow? In iOS after pressing "Copy Link", it copied a valid invite link. In Android, it's shown with valid invite link.

2023-01-26 19:41 UTC, stevemudie commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +2. Tapping the + sign in the top right corner of the mobile app opens the invite menu at the bottom of the screen
Just a menu actually. No real name for it as it contains several different things you can do. Fixed in the latest commit.

2023-01-27 11:01 UTC, saturninoabril approved these changes
Thanks Steve. I had couple comments but I'll go ahead and add via suggestions. I'm good as is. I'm also fine to address `MM-T5362` separately.

Note: The automated tests [here](https://github.com/mattermost/mattermost-mobile/blob/main/detox/e2e/test/teams/invite_people.e2e.ts#L72-L93) may need to update based on changes here (additional verification).

2023-01-27 11:02 UTC, saturninoabril commented on data/test-cases/mobile-v2/invite-people/MM-T5360.md
> +2. Tapping the + sign in the top right corner of the mobile app opens the invite menu at the bottom of the screen
Thanks Steve!

2023-01-30 19:58 UTC, stevemudie commented on data/test-cases/mobile-v2/invite-people/MM-T5362.md
> +•
Yeah, my mistake. I'm going to revert it.

2023-01-30 20:56 UTC, merged

2023-01-31 01:19 UTC, saturninoabril commented
Thanks @stevemudie! If not yet, could you help facilitate updating the automated test related to this change - https://github.com/mattermost/mattermost-mobile/blob/main/detox/e2e/test/teams/invite_people.e2e.ts#L72-L93? Thanks!