test(message_edit_post_history): New test case for edit post history
mattermost/mattermost-test-management pull request #62
Opened 2023-01-28 01:47 UTC by jgilliam17

#### Summary

Adding new test case for message edit post history. Contributor is adding Cypress test.

Jira ticket: https://mattermost.atlassian.net/browse/MM-45494

#### Is the feature in stable branch or under review?
- [] Feature in stable branch (master, main)?
- [x] Feature still under review? If yes, list all related pull requests for reference.
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/11069
Server PR: https://github.com/mattermost/mattermost-server/pull/20945
Server PR: https://github.com/mattermost/mattermost-server/pull/20945
#### Test server

https://mattermost-server-pr-21601.test.mattermost.cloud/
#### Test client

- [x] Browser
- [] Mobile App (version, OS)
- [x] Desktop App (version, OS)

2023-01-30 00:52 UTC, saturninoabril requested changes
Thanks @jgilliam17!

Is there an existing test that exercise permission on who can/cannot edit a post? If not, may be something to add? Not necessarily blocking here or for [MM-45494](https://mattermost.atlassian.net/browse/MM-45494).

2023-01-30 00:52 UTC, saturninoabril commented on data/test-cases/channels/messaging/message_edit_post_history.md
> +5. Open edit history by clicking on edited post link
re: "edited post link" - Not sure if "link" is clear to anyone reading it first. Maybe button? Could be:

```suggestion
5. Open edit history by clicking "`<pencil icon>` Edited" button of the post
```

2023-01-30 00:52 UTC, saturninoabril commented on data/test-cases/channels/messaging/message_edit_post_history.md
> +1. Get the last post id
"id" is not visible to actual user. Perhaps,
```suggestion
1. Get the last post
```

2023-01-30 00:52 UTC, saturninoabril commented on data/test-cases/channels/messaging/message_edit_post_history.md
> +3. COnfirm the resttore
```suggestion
3. Confirm the restore
```

2023-01-30 00:52 UTC, saturninoabril commented on data/test-cases/channels/messaging/message_edit_post_history.md
> +7. Check if the messsage has been updated to the correct version "This is the final version of the sample message"
```suggestion
7. Check if the message has been updated to the correct version "This is the final version of the sample message"
```

2023-01-30 18:46 UTC, jgilliam17 commented on data/test-cases/channels/messaging/message_edit_post_history.md
> +1. Get the last post id
Great point! Thanks

2023-01-31 03:04 UTC, jgilliam17 commented
> Thanks @jgilliam17!
> 
> Is there an existing test that exercise permission on who can/cannot edit a post? If not, may be something to add? Not necessarily blocking here or for [MM-45494](https://mattermost.atlassian.net/browse/MM-45494).

I'll have to check on this. I'll mention in the webapp or server PR

2023-02-02 21:36 UTC, stevemudie approved these changes

2023-02-02 21:37 UTC, merged

2023-02-02 23:48 UTC, jgilliam17 commented
@saturninoabril Can you sync with Zephyr and share test case ID please? Thanks 🙂

2023-02-02 23:58 UTC, saturninoabril commented
Hello @jgilliam17, done, MM-T5381.

2023-02-02 23:58 UTC, jgilliam17 commented
Great - thanks Saturn!