Added help resources test case
mattermost/mattermost-test-management pull request #68
Opened 2023-02-03 20:38 UTC by furqanmlk

#### Summary

Ref: https://github.com/mattermost/mattermost-webapp/pull/12026

- [x] Browser
- [x] Mobile App (version, OS)
- [x] Desktop App (version, OS)

2023-02-03 20:45 UTC, jgilliam17 requested changes
Just two suggestions, otherwise looks good.

2023-02-03 20:45 UTC, jgilliam17 commented on data/test-cases/suite/system-console/site-configuration/customization/MM-Test-Case-1.md
> +3. ***Help Link** should be empty
```suggestion
3. **Help Link** should be empty
```

2023-02-03 20:45 UTC, jgilliam17 commented on data/test-cases/suite/system-console/site-configuration/customization/MM-Test-Case-1.md
> +4. **Help Resources** option should not be exist
```suggestion
4. **Help Resources** option should not exist
```

2023-02-06 08:09 UTC, yasserfaraazkhan approved these changes

2023-02-08 21:20 UTC, merged

2023-02-10 21:13 UTC, saturninoabril commented
Test case saved - MM-T5383