Add Test cases for Co-term expansion
mattermost/mattermost-test-management pull request #7
Opened 2022-11-08 09:34 UTC by yasserfaraazkhan

2022-11-08 10:15 UTC, AGMETEOR commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +- if the current license is ending in 60 or 30 days, the expansion option is not shown
60 days to be precise

2022-11-08 10:15 UTC, AGMETEOR commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +3. If Active users are less than the Number for which license was purchased, Verify only "Download license" button is shown.
Might not be possible to know this from the portal

2022-11-08 10:15 UTC, AGMETEOR commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +5. Verify "cancel Auto-renew" option is displayed.
We have not implemented this yet

2022-11-08 10:15 UTC, AGMETEOR commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +Details should include Date (date of purchase), Description (License name and annual/pro-rata subscription), Users, Price, Total, Status (purchase status)
Unless this test will be connected to stripe, seeing the additional users after expansin might be difficult in cypress

2022-11-08 10:31 UTC, saturninoabril commented
@yasserfaraazkhan I'm reducing the reviewers. Ideal would be 2 reviewers -- one from Dev team and the other from QA guild.

2022-11-08 10:32 UTC, yasserfaraazkhan commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +Details should include Date (date of purchase), Description (License name and annual/pro-rata subscription), Users, Price, Total, Status (purchase status)
got it Allan , will update it

2022-11-08 10:32 UTC, yasserfaraazkhan commented
> @yasserfaraazkhan I'm reducing the reviewers. Ideal would be 2 reviewers -- one from Dev team and the other from QA guild.

sure Saturn,

2022-11-08 10:33 UTC, saturninoabril commented on data/TEST_CASE_TEMPLATE.md
> +status: Draft
Thanks! I'd suggest o default with `Active` since once approved, it should be used for testing.

2022-11-08 10:34 UTC, yasserfaraazkhan commented on data/TEST_CASE_TEMPLATE.md
> +status: Draft
Noted!! :)

2022-11-08 11:07 UTC, saturninoabril requested changes
Thanks @yasserfaraazkhan! LGTM, please see comments.

2022-11-08 11:07 UTC, saturninoabril commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +Verify the purchase for aditional users was successfull and purchase history page shows details of purchase.
```suggestion
Verify the purchase for additional users was successful and purchase history page shows details of purchase.
```

2022-11-08 11:07 UTC, saturninoabril commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +1. Login to portal. (or create a new account).
```suggestion
1. Login to portal or create a new account.
```

2022-11-08 11:07 UTC, saturninoabril commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +   - Content of CTA with orange border "You have exceeded your license seat count. Purchase additional seats" (if it exceeds by 5 % )
```suggestion
   - Content of CTA with orange border "You have exceeded your license seat count. Purchase additional seats" (if it exceeds by 5% )
```

2022-11-08 11:07 UTC, saturninoabril commented on data/test-cases/cloud/customer-portal/co-term-expansion/Test-Case-1.md
> +   - Content of CTA with Red border "You have exceeded your license seat count by X users. Purchase additional seats" (if it exceeds more than 10 % )
```suggestion
   - Content of CTA with Red border "You have exceeded your license seat count by X users. Purchase additional seats" (if it exceeds more than 10% )
```

2022-11-08 11:13 UTC, saturninoabril commented
@yasserfaraazkhan, in reference to [PULL_REQUEST_TEMPLATE.md](https://github.com/mattermost/mattermost-test-management/blob/main/.github/PULL_REQUEST_TEMPLATE.md):

1. Please update the PR title to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). For test case, it could be in the following format:
```
test(feature): general description of tests
```

or something like
```
test(co-term expansion): admins should be able to purchase additional seats for existing license
```

2. Also, is there a test server already up and running where we could try out and follow the test case in this PR?

2022-11-08 11:56 UTC, yasserfaraazkhan commented
>  2. Also, is there a test server already up and running where we could try out and follow the test case in this PR?

I have implemented the suggestions. Thank you @AGMETEOR and @saturninoabril

@saturninoabril , the changes are in 2 PR separately. After the initial set-up changes go in, I'll write more scenario with hands-on UI.

2022-11-08 22:56 UTC, saturninoabril commented
Removing LM for I'll represent the QA review.

2022-11-10 08:47 UTC, yasserfaraazkhan commented
Hi @AGMETEOR @saturninoabril ,
I updated one condition and will be merging the PR.

2022-11-10 08:48 UTC, merged