chore(actions): test-0
mattermost/mattermost-test-management pull request #79
Opened 2023-03-07 13:04 UTC by yasserfaraazkhan

2023-03-07 13:51 UTC, saturninoabril requested changes
Thanks Yasser, looking good, except for few comments.

Should this PR limit the change to `.github/workflows/deno.yml`? If yes, please revert changes to other unrelated files.

2023-03-07 13:51 UTC, saturninoabril commented on .github/workflows/deno.yml
> +        if: ${{ github.event_name == 'pull_request' && github.ref == 'refs/pull/79/merge' }}
Maybe `refs/pull/79/merge` is not intended?

2023-03-07 13:51 UTC, saturninoabril commented on .github/workflows/deno.yml
> +          commit_user_email: yasser.khan@mattermost.com
Should we use https://github.com/mattermost-quality instead?

2023-03-07 13:51 UTC, saturninoabril commented on .github/workflows/deno.yml
> +        run: deno task save
In some case, there is malformed markdown being saved and requires quick review and correction. How are we going to deal with that?

2023-03-07 13:53 UTC, yasserfaraazkhan commented
noted @saturninoabril , 
will add the make the changes as suggested.

Wanted to check 
- at what schedule time it should run?
- it should also run when there is a Push to Main branch, right?

2023-03-07 13:56 UTC, saturninoabril commented
> it should also run when there is a Push to Main branch, right?

Yes, push and merge to main branch.

> at what schedule time it should run?

Maybe no need to have a cron job for daily run since any sync will happen whenever there's push/merge to main. Thoughts?

2023-03-07 14:08 UTC, yasserfaraazkhan commented on .github/workflows/deno.yml
> +        run: deno task save
I will remove this to just point at main branch...for sometime using it for testing out changes

2023-03-09 02:49 UTC, saturninoabril commented on .github/workflows/deno.yml
> +      - cron: '00 1 * * 1'
Hello Yasser, should we still run cron job regularly or sync should happen only during merge/push to main?

2023-03-09 10:21 UTC, yasserfaraazkhan commented on .github/workflows/deno.yml
> +      - cron: '00 1 * * 1'
Hi @saturninoabril 
I'm thinking of having `workflow_dispatch` added and remove cron.
we can just run it manually in actions, if we want. (also it will run when merged)

2023-03-09 11:34 UTC, saturninoabril approved these changes
Thanks @yasserfaraazkhan !

2023-03-09 11:34 UTC, merged