Feat: Cloud Free Deprecation test case
mattermost/mattermost-test-management pull request #86
Opened 2023-03-28 10:03 UTC by yasserfaraazkhan

- Epic : https://mattermost.atlassian.net/browse/MM-51411

2023-03-29 08:52 UTC, AGMETEOR commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +1. Repeat above steps but verify that Global banner and CTA now has red background color.
Do we also want to test scenario of the dismissable banner reappearing, (after dismissal) at the 60, 30, 10 days to deprecation interval

2023-03-30 04:52 UTC, yasserfaraazkhan commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +1. Repeat above steps but verify that Global banner and CTA now has red background color.
sure Allan, I'll add a step for it.

2023-04-03 00:27 UTC, johndavidlugtu requested changes
@yasserfaraazkhan good stuff so far!

We'll also want to verify banners inside the system console are also visible.

Also, can we also make add to verify everything mentioning "Cloud Free" and not "Cloud Starter"? Thanks

2023-04-03 00:27 UTC, johndavidlugtu commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +6. When User clicks on `Contact Sales` button, verify Zendesk form is opened in a new Tab
Actually, any "Contact Sales" button should redirect to mattermost.com/contact-sales

"Contact support" will be the one that redirects to Zendesk

https://mattermost.atlassian.net/browse/MM-51682

2023-04-03 09:31 UTC, AGMETEOR commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +1. Repeat above steps but verify that Global banner and CTA now has red background color.
There's another test case for the changes in the pricing modal here https://github.com/mattermost/mattermost-server/pull/22639

2023-04-04 10:05 UTC, yasserfaraazkhan commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +6. When User clicks on `Contact Sales` button, verify Zendesk form is opened in a new Tab
Sure John, I've updated the changes

2023-04-05 05:30 UTC, yasserfaraazkhan commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +1. Repeat above steps but verify that Global banner and CTA now has red background color.
Thank you @AGMETEOR , I've added a test for this

2023-04-07 22:12 UTC, lindalumitchell approved these changes
Approving, with just a few very minor suggestions. :)

2023-04-07 22:12 UTC, lindalumitchell commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +2. Verify Global Banner with a message 'Cloud Free will be depreicated on MM DD YYY. To keep your workspace, upgrade to a paid plan.'
```suggestion
2. Verify Global Banner with a message 'Cloud Free will be deprecated on MM DD YYY. To keep your workspace, upgrade to a paid plan.'
```

2023-04-07 22:12 UTC, lindalumitchell commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +3. Navigate to System console > Subscriptions
```suggestion
3. Navigate to System Console > Subscriptions
```

2023-04-07 22:12 UTC, lindalumitchell commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +7. Clicks on the `Upgrade` button, verify Plans modal is opened
```suggestion
7. Click on the `Upgrade` button, verify Plans modal is opened
```

2023-04-07 22:12 UTC, lindalumitchell commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +8. Click on `Upgrade` button on `Professional` card.
```suggestion
8. Click on `Upgrade` button on `Professional` card
```

2023-04-07 22:12 UTC, lindalumitchell commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +12. Verify the Upgrade is successful and license is applied. (Navigate to channels and verify `view plan` is not be shown on the top right of banner)
```suggestion
12. Verify the Upgrade is successful and license is applied. (Navigate to channels and verify `view plan` is not shown on the top right of banner)
```

2023-04-07 22:12 UTC, lindalumitchell commented on data/test-cases/cloud/cloud-free-deprecation/test-1.md
> +Scenario 3: Dismissed Global Banners should reappear after Admin
```suggestion
Scenario 3: Dismissed Global Banners should reappear after Admin dismisses and logs out and back in
```

2023-04-17 12:47 UTC, merged