Feat: Cloud Trial Lifecycle
mattermost/mattermost-test-management pull request #90
Opened 2023-04-05 12:39 UTC by yasserfaraazkhan

Epic Link : https://mattermost.atlassian.net/browse/MM-50719

2023-04-06 22:19 UTC, johndavidlugtu requested changes

2023-04-06 22:19 UTC, johndavidlugtu commented on data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-1.md
> +3. Verify the Global banner is displaed with the message `Your 30-day Enterprise trial has started! Purchase before MM-DD to keep your workspace.` and `Review your options` button
Can we add to the test "Review your options" to open up the pricing modal?

2023-04-06 22:19 UTC, johndavidlugtu commented on data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-1.md
> +2. Verify `Contact us` and `Host your own instance` buttons are shown
Can we verify "Contact us" goes to mattermost.com/contact-sales and "Host your own instance" goes to mattermost.com/download?

2023-04-11 20:57 UTC, lindalumitchell commented
Just to note that I'm holding off on my review until the above changes are made (or not). :)

2023-04-12 06:27 UTC, yasserfaraazkhan commented
@lindalumitchell 
this is up for review now 😄

2023-04-12 12:07 UTC, AGMETEOR commented on data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-2.md
> +name: "Cloud Evaluation Trial | User should be able to purchase a Plan within 30 days trial period"
Can only self-serve a professional plan

2023-04-13 15:24 UTC, yasserfaraazkhan commented on data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-2.md
> +name: "Cloud Evaluation Trial | User should be able to purchase a Plan within 30 days trial period"
Oh!! I picked it from figma, it shows `Purchase` button for Enterprise 
@AGMETEOR , will enterprise card show `contact sales` in this case?

2023-04-17 19:41 UTC, AGMETEOR commented on data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-2.md
> +name: "Cloud Evaluation Trial | User should be able to purchase a Plan within 30 days trial period"
> Oh!! I picked it from figma, it shows `Purchase` button for Enterprise @AGMETEOR , will enterprise card show `contact sales` in this case?

Yes Enterprise card only shows contact sales

2023-04-17 21:39 UTC, johndavidlugtu commented on data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-1.md
> +1. The Global banner should display a message `This is the last day of your free trail. Purchase a plan before 11.59pm PT or contact sales` and `Review your options` button
@AGMETEOR here's the Jira ticket about that: https://mattermost.atlassian.net/browse/MM-51479

@yasserfaraazkhan minor thing: typo on "trial"

2023-04-18 06:32 UTC, yasserfaraazkhan commented on data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-2.md
> +name: "Cloud Evaluation Trial | User should be able to purchase a Plan within 30 days trial period"
done

2023-04-18 06:32 UTC, yasserfaraazkhan commented on data/test-cases/cloud/cloud-trial/cloud-evaluation-trial/test-1.md
> +1. The Global banner should display a message `This is the last day of your free trail. Purchase a plan before 11.59pm PT or contact sales` and `Review your options` button
done

2023-04-18 21:18 UTC, lindalumitchell approved these changes
Thanks Yasser! LGTM 👍

2023-04-19 10:09 UTC, merged