Added Keyboard shortcuts test case
mattermost/mattermost-test-management pull request #91
Opened 2023-04-05 20:41 UTC by furqanmlk

2023-04-07 16:05 UTC, stevemudie approved these changes
Looks good @furqanmlk!

2023-04-07 16:07 UTC, stevemudie commented
@furqanmlk I just had a thought about this though. 🤔 

This will affect the current keyboard shortcuts listing in-app. Is there a ticket and/or PR to make the needed change there as well?

2023-04-07 22:17 UTC, lindalumitchell requested changes
Just a few suggestions. :)

2023-04-07 22:17 UTC, lindalumitchell commented on data/test-cases/channels/keyboard-shortcuts/MM-Test-Case-1.md
> +name: "Allow CTRL/CMD + K to insert link formatting when text is selected"
Should be `V` instead of `K`?

2023-04-07 22:17 UTC, lindalumitchell commented on data/test-cases/channels/keyboard-shortcuts/MM-Test-Case-1.md
> +name: "Allow CTRL/CMD + K to insert link formatting when text is selected"
```suggestion
name: "Allow CTRL/CMD + V to insert link formatting when text is selected"
```

2023-04-07 22:17 UTC, lindalumitchell commented on data/test-cases/channels/keyboard-shortcuts/MM-Test-Case-1.md
> +3. Type **Github**
```suggestion
3. Type **Github** into message or reply input box
```

2023-04-07 22:17 UTC, lindalumitchell commented on data/test-cases/channels/keyboard-shortcuts/MM-Test-Case-1.md
> +4. Select a text and paste or press cmd/ctrl+v
```suggestion
4. Select the text you typed, and paste or press CMD/CTRL+V
```

2023-04-07 22:17 UTC, lindalumitchell commented on data/test-cases/channels/keyboard-shortcuts/MM-Test-Case-1.md
> +5. Press enter
```suggestion
5. Press Enter
```

2023-04-07 22:17 UTC, lindalumitchell commented on data/test-cases/channels/keyboard-shortcuts/MM-Test-Case-1.md
> +4. **Github** should be shown as a hyperlink
```suggestion
4. **Github** should be shown as a hyperlink to https://github.com
```

2023-04-18 21:19 UTC, lindalumitchell approved these changes
Thanks Malik! LGTM 👍

2023-04-19 10:51 UTC, merged

2023-04-19 12:10 UTC, saturninoabril commented
Test case added as MM-T5421 - https://github.com/mattermost/mattermost-test-management/commit/6cf2eb454f7530265a634a9abbf248917de043f3#diff-47db6cd1a850f844f80a85761d88229e51d3136adcad1a1660795dbd4cbba246R28